### ISSUE TITLE
DateTime Filters not working

### ISSUE THREAD

**Issue by gmiserez** [ChilliCream/hotchocolate#1036]
Hello,
We're running the HotChocolate PRISMA-like Filters on top of a MongoDB. 
We're currently experiencing troubles with filters on DateTimeType Fields. 

**To Reproduce**
A sample repository is available here: 
https://github.com/gmiserez/HotChocolate_DateTimeFilterIssues

Here are our queries: 
```
query allConcerts
{
  blackSabbath2019Tour {
    concertDate
    name
  }
}
query allConcertsOf2019
{
  blackSabbath2019Tour(where: { concertDate_gte: "2019-06-01T08:00:00.000Z" }) {
    concertDate
    name
  }
}
query allConcertsOnExactDate
{
  blackSabbath2019Tour(where: {concertDate: "2019-06-01T08:00:00.000Z"}){
    concertDate
    cityName: name
  }
}
```

The first query returns this:
```
  "data": {
    "blackSabbath2019Tour": [
      {
        "concertDate": "2019-06-01T08:00:00.000Z",
        "name": "Amsterdam"
      },
      {
        "concertDate": "2019-07-10T08:00:00.000Z",
        "name": "Berlin"
      },
      {
        "concertDate": "2019-06-18T08:00:00.000Z",
        "name": "Paris"
      },
      {
        "concertDate": "2019-03-15T08:00:00.000Z",
        "name": "Zürich"
      }
    ]
```

The second query returns an error:
> The binary operator GreaterThanOrEqual is not defined for the types 'System.DateTime' and 'System.DateTimeOffset'.

Third query:
> The binary operator Equal is not defined for the types 'System.DateTime' and 'System.DateTimeOffset'.

**Expected behavior**
Ideally it should be possible to filter on DateTime fields. However I don't know if this can be fixed in HotChocolate or if this issue is with the MongoApi itself. 

**Packages:**
- HotChocolate.* 11.0.0-preview.4
- MongoDB.Driver 2.8.1

**Comment by shalvin** [comment]
I had this same issue. I ended up changing `DateTimeType` to `DateType` for my date field. In your sample's `CityType`, you could change the type to be `DateType`.

`descriptor.Field(c => c.ConcertDate).Type<NonNullType<DateType>>();`

The `DateTimeType` uses the CLR type `System.DateTimeOffset`, whereas the `DateType` uses `System.DateTime`.

I think the cause is confusion between the naming of `DateType` vs `DateTimeType`. I would expect `DateTimeType` to use the CLR type `System.DateTime`. Is this naming intentional?

**Comment by michaelstaib** [comment]
This one works now in V11 and V10.

#1170
