### ISSUE TITLE
Authorization with JWT

### ISSUE THREAD

**Issue by AALGate** [ChilliCream/hotchocolate#1103]
When i used Web API , i used the attribute [Authorize] above the controller
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]

i have installed the Authorization package of hotchocolate.

I wonder how i can reach the same approach with 
`descriptor.Authorize();`
in my overrided configuration method

how i can pass "AuthenticationSchemes "  to the Authorize() method

-----------------------------------------------
I have another small question:
how i can fetch the Context ?

**Comment by michaelstaib** [comment]
Hot Chocolate provides directives for authorization but does not do authentication. The bearer schema has to be configured with authentication. 

For authentication refer to the ASP.NET documentation.

Once you have setup authentication you can use use policies, roles or just the authenticated check provided by the authorize directives.

https://hotchocolate.io/docs/authorization

**Comment by michaelstaib** [comment]
> how i can fetch the Context ?

If you mean the HttpContext then register the `IHttpContextAccessor` and use dependency injection.

**Comment by AALGate** [comment]
> > how i can fetch the Context ?
> 
> If you mean the HttpContext then register the `IHttpContextAccessor` and use dependency injection.

Thanks a lot for the help.

But, i have tried fetching the context with `IHttpContextAccessor`  before i created this issue. unfortunately, not all properties are fetched !

for example the `body` stream, is not fetched !

**Comment by michaelstaib** [comment]
What do you actually want to do?

**Comment by AALGate** [comment]
well, i tried to catch the body as a stream

the body, i mean, the query itself

**Comment by michaelstaib** [comment]
You cannot do that since the middleware has already consumed the body. You can however access the parsed body through the `IResolverContext`.

**Comment by orlandommb** [comment]
hi @michaelstaib ! maybe this would need to be reopened, in my case a i got a asp.net core blazor server app, i mead the whole app is server rendered, i have a few apis implemented for basic usage im planning on using hotchocholate so i can make a client app and get rid of the server rendered components, but as of now i need to specify the [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)] in the controllers so they can work with JWT and the blazor asp.net core identity authorization can work too. i don't if i explained the whole picture correctly, but i the thing is i cannot set the JWT as default authoorization request as of now because that would disrupt the whole app authenticacion process.

I think adding the AuthenticationSchemes parameter to Autorization attribute would be a life saver here.

**Comment by orlandommb** [comment]
im going to open another issue with this same comment

> hi @michaelstaib ! maybe this would need to be reopened, in my case a i got a asp.net core blazor server app, i mead the whole app is server rendered, i have a few apis implemented for basic usage im planning on using hotchocholate so i can make a client app and get rid of the server rendered components, but as of now i need to specify the [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)] in the controllers so they can work with JWT and the blazor asp.net core identity authorization can work too. i don't if i explained the whole picture correctly, but i the thing is i cannot set the JWT as default authoorization request as of now because that would disrupt the whole app authenticacion process.
> 
> I think adding the AuthenticationSchemes parameter to Autorization attribute would be a life saver here.
