### ISSUE TITLE
Rewriting remote error paths

### ISSUE THREAD

**Issue by nigel-sampson** [ChilliCream/hotchocolate#1112]
Just wanted to start a discussion about remote error paths during schema stitching.

Currently if the server doesn't return a path on the error then `DelegateToRemoteSchemaMiddleware` doesn't add a path to the error object. This means for things like HTTP errors or other errors from the remote schema then on the stitched schema we don't have any error path to make diagnostic decisions.

Would it make sense to simply add the `context.Path` as the `error.Path` when there is no remote error?

**Comment by michaelstaib** [comment]
My reasoning behind that decision was that if there is no path that it is actually a global error. If we now add a path this could lead to errors be added to fields that they do not belong to.

While this might not be a problem with a single call it becomes a problem with batching. 

The stitching layer merges multiple requests sends those to the remote schema in one call and after receiving the result delegates the results to the requesting resolvers.

Global errors (errors without path) are send to one of those resolvers since it really does not matter to which resolver the error is added. If we now add a path we would get these error randomly associated.

https://github.com/ChilliCream/hotchocolate/blob/ad98d70aa2f9a627f8ba83a893fdf41250ff3322/src/Stitching/Stitching/Client/RemoteRequestDispatcher.cs#L82

**Comment by michaelstaib** [comment]
Concerning HTTP errors. The errors are actually not remote errors but errors in the stitching layer itself so we should be able to set the context where they occur.

**Comment by nigel-sampson** [comment]
That does make sense, one issue here is that a global error on a field stitched in deep in the query looks a lot like a global error on the whole query.

I'll put together a PR for the HTTP case, 

I think it may be a good idea to add the schema name as an extension on these errors at the same time to give a bit more context for global errors.

**Comment by d0as8** [comment]
Hi! How about this case: some provider returns path with empty array ("path": [])? so, HC 13.9.15 crashes with "Index was outside the bounds of the array." error in RewriteErrorPath. Recommends?
