### ISSUE TITLE
DataLoader needing an option for fixed expiring interval (not sliding).

### ISSUE THREAD

**Issue by tohagan** [ChilliCream/hotchocolate#1163]
**Is your feature request related to a problem? Please describe.**

To keep Authorization checks performant, I need to load and cache user objects that have roles which are loaded from an external database or AD service (not in a token claim). Sliding cache expiration is incorrect as that keeps user roles cached for an indeterminate interval when we need them to be expired after a *fixed time interval* since last load to ensure that user role changes are always enacted after a known fixed time interval. I suspect this cache behavior is more widely applicable for many common use cases beyond just my my scenario.

**Describe the solution you'd like**
I need a DataLoaderOption attribute that causes the cache to expires a key after a fixed interval since it was last loaded (not a sliding interval).

**Describe alternatives you've considered**
Ignore the DataLoader API and create my own caching class.  

**Additional context**
Since Authorization checks are performed early in the request life cycle (to avoid loading unauthorized contents) and dataloaders are resolve late (to permit batching), using a DataLoader may be incorrect use of the API. I suspect not because I can use GreenDonut API independently of the HotChocolate API.

**Comment by tohagan** [comment]
I noticed that GreenDonut has it's own `TaskCache.cs` for managing sliding time caching.

At a quick glance, it looks to me as though it's implementing the same logic as [IMemoryCache](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.0#use-imemorycache) which supports both sliding and absolute timespan cache expiration.

Here's a [thread safe code sample](https://www.hanselman.com/blog/TheProgrammersHindsightCachingWithHttpClientFactoryAndPollyPart2.aspx) for using it.

**Comment by michaelstaib** [comment]
> using a DataLoader may be incorrect use of the API

It is not incorrect and we use DataLoader also without HC in some projects.

I do not see distributed caches relevant for DataLoader in the near future. We pondered the idea of `IMemoryCache` but abandoned it very early for both HC caching and GD caching because it brings configuration and logging dependencies with it that might not be wanted in some cases.

I think I will talk to a few people about `IMemoryCache` again :) thinks like that are worth to reevaluate.

I think the nice thing from a GD perspective is that it has almost no external dependencies. Which avoids diamond dependencies and issues caused by them.

From an HC perspective this is also a consideration worth but not as much since we decided to use the dependency injection from `Microsoft` in the core. Although, the DI can be swapped out the core has a dependency on that. So, having one more dependency or providing an abstraction for the ms cache implementation is feasible. 

We will talk this through.

When we change the foundation (move to `IMemoryChache`) this would be a major change. This means we would then move this issue to version 11 (end of January).

**Comment by michaelstaib** [comment]
We have talked this one through today.

At the moment GreenDonut and HotChocolate have their own distinct cache implementations. With GreenDonut we decided back when we started that we wanted to have something small and efficient without any dependencies. 

We kind of decided to day to shake that a little up.

1) GreenDonut will refine its cache more, so we will take what we learned in both projects and put that into the GreenDonut implementation.

2) We will remove the HC cache implementation and use the GreenDonut cache for things like query caching and stuff like that.

3) Since GreenDonut provides an abstraction the internal cache can be swapped out for any other cache implementation. We will provide a separate package that allows to use `IMemoryCache` with HC and GD instead of the internal cache.

So, when GD is used without HC or in a different way then we have envisioned it will be possible to easily swap out the cache implementation.

4) We will add the DataLoader base classes for GroupDataLoader and so on to the GreenDonut library making it easer to create DataLoader with HC and other platforms. 

@rstaib what do you think?

**Comment by tohagan** [comment]
That all make perfect sense.  I suspect that longer term, MS will continue to enhance their caching (and distributed caching) APIs and you'd want to be able have the option to leverage if needed but correctly abstract it so you'd stuck with it or dependent on it.

For now ... I can around my needs by using IMemoryCache directly in the one place I need it for this caching behavior so no rush at my end. 

Thanks @michaelstaib . You're doing a wonderful consultative job!

**Comment by rstaib** [comment]
@michaelstaib I have nothing to add here since you have already mentioned all the points we discussed yesterday through.

@tohagan Thank you for your contribution!

**Comment by tohagan** [comment]
Awesome!
