### ISSUE TITLE
Server seems to have a memory leak

### ISSUE THREAD

**Issue by Eebo78** [ChilliCream/hotchocolate#1330]
**Describe the bug**
Memory keeps on increasing when running the server and sending queries

**To Reproduce**
1. Create a new server from the template
2. Start the server 
3. Open your browser and navigate to playground
4. If running from visual studio you can see that memory keeps increasing or in task manager

**Expected behavior**
Memory should not keep on increasing after requests

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
No different behavior if server is hosted with kestrel or IIS express. Same behavior when using Graphiql, but here you have to go triggerhappy on the play button

**Comment by michaelstaib** [comment]
So, the memory increases when you send queries or on its own?

**Comment by Eebo78** [comment]
It's increasing when sending queries. Playground sends schema queries on an interval. Graphiql doesn't so here I have to create an query and click the play button to see that it increases.

**Comment by michaelstaib** [comment]
OK,

we are working on doing something for that. 

But, there always will be an impact for queries since we have to build up the result. We will mitigate some of the effects with pooled objects but not all.

Schema polling is not a good idea since you have to constantly create a result for the introspection query and that costs.

We have one user that has a schema that is about 50mb big when serialized as a result. Facebooks introspection result is about 200mb. Doing schema polling in schemas like that will always be a problem.

**Comment by michaelstaib** [comment]
I have marked this issue as duplicate since we are tracking this already.

**Comment by Eebo78** [comment]
OK, but I see the same behavior when using GraphiQL. Afaik this doesn't do schemapolling and a running following: query test { greetings { hello}} increases the memory usage? Will that be fixed in the duplicate ticket?

**Comment by michaelstaib** [comment]
Are you testing this with debugger attached?  The overall overhead for this query should be minimal.

But rest assured, we have this on our list and will address the allocations with the upcoming V11.

**Comment by michaelstaib** [comment]
#1283

**Comment by michaelstaib** [comment]
Just so you know, we also have a slack channel for questions.... 
https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q
