### ISSUE TITLE
[Banana Cake Pop] release as ASP.Net Core middleware

### ISSUE THREAD

**Issue by OneCyrus** [ChilliCream/hotchocolate#1359]
it would be awesome if we could get banana cake pop as an ASP.Net Core middleware like `HotChocolate.AspNetCore.Playground` or `HotChocolate.AspNetCore.GraphiQL`

no need to install an application on every system and keeping them up to date makes web applications much more accessible.

**Comment by rstaib** [comment]
At the moment we are focused on getting things done for version 1.0. It's not yet decided whether we even want to offer a browser compatible variant of Banana Cake Pop (which will by the way support auto-update and therefore be always up-to-date), because we're more thinking of creating an application like Postman but for GraphQL (feature rich, powerful and perhaps not as lightweight as a browser app should be in my opinion). However I'm definitely open for discussion on that topic and internally we're already discussing it. Thank you for your feedback.

**Comment by michaelstaib** [comment]
I also have concerns with a web variant since it would draw our focus away from the actual product we are trying to build. I think we rather should take the new GraphiQL on Monaco version that Riki is building and building on top of that a browser implementation that is small and less feature rich. 

But I see a need for a better browser tooling since the current playground and graphiql middleware are not sufficient. I think we will get rid of them and focus on one particular one.

**Comment by michaelstaib** [comment]
I think we will have to talk about this when we focus back on the server end of January.

**Comment by PascalSenn** [comment]
I think this one it done 🚀 
@OneCyrus  have you seen it in the 11 previews? :)

**Comment by OneCyrus** [comment]
good start. are there some extensibility points and how is the identity provider story?

**Comment by PascalSenn** [comment]
@rstaib  is working on Identiy

**Comment by michaelstaib** [comment]
Btw, can we close this one and create rather specific feature requests than adding points to this discussion? It is better trackable if we have dedicated requests. We have authentication flows on our list. I will have a look with Phillipe next week on how we can make this work.
