### ISSUE TITLE
UseFiltering with string properties results in ID input types

### ISSUE THREAD

**Issue by freever** [ChilliCream/hotchocolate#1384]
I have a user entity with a string FirstName property:
```c#
public string FirstName { get; private set; }
```

I have a FilterInputType defined with a filter to allow searching by FirstName:

```c#
descriptor
    .Filter(x => x.FirstName)
    .BindFiltersExplicitly()
    .AllowContains();
```

This produces an input type in my schema with a firstName_contains property, but it is of type ID:

```graphql
input UserFilter {
  firstName_contains: ID
}
```

Should this not be String type?

**Comment by PascalSenn** [comment]
Hi @freever  
Do you use any Graphql Attributes in the model?

**Comment by freever** [comment]
@PascalSenn Nope, my entity class is an EF Core POCO domain class. 

The UserType in my QueryType defines FirstName as StringType:

```c#
descriptor.Field(x => x.FirstName)
    .Name("FirstName")
    .Type<StringType>();
```

**Comment by michaelstaib** [comment]
this is fixed on the 11 branch.

with 10 consider in this case to explicitly bind string to string type

```
SchemaBuilder.New()
    .BindClrType<string, StringType>()
    ...
```

**Comment by michaelstaib** [comment]
The issue here is that the `ID` type was discovered first and registered as type for string. So all consecutive `System.String` are now becoming `ID`.

since

```
descriptor
    .Filter(x => x.FirstName)
    .BindFiltersExplicitly()
    .AllowContains();
```

does not define the type it is inferred and it is inferred as ID

with the bind specification you basically force it to a specific type.


in 11 we can now specify the binding strategy of a scalar:

https://github.com/ChilliCream/hotchocolate/pull/1386

**Comment by michaelstaib** [comment]
Can we close this? Is it solved with the explicit bind?

**Comment by freever** [comment]
I haven't tried yet... go ahead and close it i will reopen it if I can't
solve it that way
