### ISSUE TITLE
[Berry] Generate client code with authentication parameters in methods

### ISSUE THREAD

**Issue by josheleonard** [ChilliCream/hotchocolate#1392]
I have paths in my scheme that are marked with the [Authorize] directive attribute, but the code that was generated from `dotnet build` does not include parameters to attach/change authorization headers to the request other than setting a default.

Is there a workaround for now to add/change an auth header per request?

**Comment by michaelstaib** [comment]
Actually there is. 

The main idea here is that you configure your `HttpClient` through the `IHttpClientFactory`. With the IHttpClient factory you can configure how to swap tokens out. Each time you get a client from the dependency injection you actually gat a configured client for that particular session.

But I can see that you want to pass something on a method level in. So we will allow you with the next update to pass in extension properties. They are actually already there but not accessible through the main interface. With that you can pass any properties into the execution pipeline.

The execution pipeline is modular and you can add your own middleware to it.
https://github.com/ChilliCream/hotchocolate/blob/26f4d521867f5e7ba5cf7c60955701e491a3e8b0/src/Client/Demo/StarWarsQuery/Generated/StarWarsClientServiceCollectionExtensions.cs#L43

so if you take the above demo we could add a middleware like the following:

```csharp
services. AddStarWarsClient()
    .AddHttpOperationPipeline(builder => builder.Use(...).UseHttpDefaultPipeline());
```  

With that you gain access on the request processing... you can then map extensions properties to the request message if you wish to do so.

As I said you will need for the next strawberry update so that you can send custom props in.

**Comment by PascalSenn** [comment]
@josheleonard 
Authentication Docs:
https://github.com/ChilliCream/hotchocolate/pull/3315
