### ISSUE TITLE
Perfomance issue with serialization.

### ISSUE THREAD

**Issue by traitmmm** [ChilliCream/hotchocolate#1408]
Hello.
Could you help me with current serialization issues under hotchocolate-graphql.
As I understand current flow is: 

Query -> [return List of Objects] -> `ConverterToDictionaries` Somewhere inside hotchocolate this models convert to OrderDictionaries -> `IQueryResultSerializer` `[JsonQueryResultSerializer]` will be convert to Json/String/Bytes. 

But I faced with issue that `JsonQueryResultSerializer` have not a good performance. 
What is the best way change `ConverterToDictionaries` and return proper data (list of objects) instead of OrderDictionaries. Is it possible to change this part of code?

**Comment by michaelstaib** [comment]
Hi,

we are working on this for version 11. With the new execution engine this will be very efficient. 

But we cannot use like concrete models since we have to follow the spec. The spec specifies the result as map and also that the result has to be ordered the way the query is defined. 

Also you have things like non-null error propagation that demand a representation of this graph in an object form...

But we have fixed the performance issues around this especially the memory consumption.

Also we have a much faster serializer that builds upon Microsofts json serialized.

I will give you a ping once the first preview of the execution engine drops.

**Comment by traitmmm** [comment]
Hello.
Thank you for your quick reply. 
in case you are interested: my models looks like:

```c# 
class Recipe {
    public String Name {get; set;}
    public List<Ingredient> Ingredients {get; set;}
}
// Ingredient = [id: Guid, name: String, statrus: enum]
```

when we have response with 50 Recipes and every include around ~100 Ingredients, serialization process is slow.

>But we cannot use like concrete models since we have to follow the spec

Is it possible to change order of handling?
Current: Models -> Order Dictionary and Reduce Fields -> ToJson.

and make something like:

Models -> ToJson -> Reduce Fields

Thanks.

**Comment by michaelstaib** [comment]
> Models -> ToJson -> Reduce Fields

This is not possible since GraphQL is transport agnostic. Serialization is handled after processing. 

We have reworked how we handle results and are now reusing result objects.

I will close this issue.
