### ISSUE TITLE
how to use relay schema-unique ids in queries and mutations

### ISSUE THREAD

**Issue by engenb** [ChilliCream/hotchocolate#1422]
Hello - loving me some HotChocolate!  Keep up the awesome work!

### Where I'm at:
I've got all my queries set up, via a code-first approach.  I've also enabled relay support, but I am not using the relay client (although this is something I may consider in the future)

### Where I'm going:
Now that I can query some data, I need the ability to update records via mutations.  All the Ids returned from queries appear to be a Base64 encoded value of the respective schema type + the actual Id (with a "g" prefix, for some reason?)

### Where I'm stuck:
Anywho - I'm expecting (hoping?) there must be some way to use these encoded Ids directly with other queries and mutations, but I can't find how/where to configure mutation definitions (code-first) that the inbound `IdType` is a `NodeType` encoded Id and should be decoded as such.

### What I've tried:
- defined a simple `IdType` mutation argument, but this throws an exception as the encoded Id string cannot be converted to a `Guid` to be passed to my resolver function (not seeing how/where to configure a decoder for the argument)
- defined an `InputType<T>` class, but didn't see any way to configure that the Id property was a `NodeType` Id (was hoping to find something similar to `IObjectTypeDescriptor<T>.AsNode()` but no dice.

### Questions:
- Is there documentation on this that I simply have not found yet?
- Am I expected to parse the schema-unique `NodeType` Id client-side in order to use my actual Id for subsequent queries/mutations?  This wouldn't be a big deal - a pretty simple `.map(...)` but I want to follow best practices/intended approach if I can.
- Is there a way to configure a mutation to accept/decode `NodeType` Id encoded parameters and "bind" the contained Id to a resolver argument?

Thanks for taking a look.

**Comment by michaelstaib** [comment]
> Is there documentation on this that I simply have not found yet?

Not yet. With 10.3.x this can already all be done but documentation is a bit skinny on that. Also I myself find the way not really nice :) But I can help you along on this one and show you some code examples.

For V11 we are working to get this much nicer.

> Am I expected to parse the schema-unique NodeType Id client-side in order to use my actual Id for subsequent queries/mutations? This wouldn't be a big deal - a pretty simple .map(...) but I want to follow best practices/intended approach if I can.

No, we have an IIdSerializer which is registered with your dependency injection.... so you can inject it into your resolver and it will deserialize the string on the input types for you.

```csharp
 [UseSorting]
        public Task<IReadOnlyList<Schema>> GetSchemasByIdAsync(
            [GraphQLType(typeof(NonNullType<ListType<NonNullType<IdType>>>))]string[] ids,
            [Service]IIdSerializer idSerializer,
            [DataLoader]SchemaByIdDataLoader dataLoader,
            CancellationToken cancellationToken)
        {
            if (ids.Length == 0)
            {
                throw new GraphQLException("No ids where provided.");
            }

            var deserializedIds = new Guid[ids.Length];

            for (int i = 0; i < ids.Length; i++)
            {
                IdValue deserializedId = idSerializer.Deserialize(ids[i]);

                if (!deserializedId.TypeName.Equals(nameof(Schema), StringComparison.Ordinal))
                {
                    throw new GraphQLException("The specified id type is invalid.");
                }

                deserializedIds[i] = (Guid)deserializedId.Value;
            }

            return dataLoader.LoadAsync(deserializedIds, cancellationToken);
        }
```

But that is also what I do not like at the moment... We are aiming to make this fully transparent with the new execution engine.

So expect this code to become obsolete with V11

> Is there a way to configure a mutation to accept/decode NodeType Id encoded parameters and "bind" the contained Id to a resolver argument?

We will make the fully transparent. We have are still experimenting on this one and will only become public once we add the new execution engine.... we are thinking end of march.

Also, head over to our slack channel since it is very active and you will find help there often in minutes :)

https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q

**Comment by engenb** [comment]
oh great, @michaelstaib!  thanks, that will work!  and I'll head over to the slack channel if I have any further questions
