### ISSUE TITLE
Restructuring the documentation 

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#1485]
# Update (2020-05-16) 
We came uf with the following structure in todays meeting: 

- Introduction
- Get started with Apollo Server

- Defining a Schema
--- Schema Basics 
------- Flavours
-----------Pure Code First 
-----------Code First
-----------Schema First
------- Introduction GraphQL
------- Supported types
-----------Object Types
-----------Enums 
----------- ...
------- Documentation 
------- Naming Conventions  
------- Design mutations !! 
------- ... 
--- Unions and Interfaces  (Apollo Examples)
--- Scalars (Apollo Examples)
--- Directives 
- Fetching Data 
--- Resolvers 
-------  Defining a resolver 
------- Resolver chains 
------- Resolver Arguments 
------- DI and stuff
------- Resolver Pipeline 
------- Error Handling
--- Fetching from Databases
--- Fetching from REST
--- Data Loader
--- Pagination
------Pagination Amount 
--- Filtering
--- Sorting
- Realtime Data 
---  defer
---  stream 
--- ... 
- Stiching 
--- TBD
- Testing 
---  Integration Testing
---  GraphQL Playground
- Security  
---   Introduction 
--- --- ref to Pagination Amount 
---  --- Execution Time 
---  Authroization
---  Query Complexity  
---  Protecting Playground  

---  API Reference 
------ ... 
------ Middleware
------Persisted Queries  
------ Batching 
>
--- 
# Restructuring the documentation 

Currently under the discussion in the workgroup

##  Some Community Comments on Slack
*Jeff 8 days ago*
> I had a note earlier on that I think we could make a more clear path through the docs based on whether you're doing pure code first, code first, or schema first

*Michael  8 days ago*
> Yes and there was a suggestion on tabs

*Jeff  8 days ago*
> Another option would be to make the API stuff even more technical, and move guidance and opinionated approaches to a separate section

>that seems reasonable to me, I think the issue now is the mix of technical specs and being able to convey the intended patterns of use are a little mix-and-match

*Daniel Gut  8 days ago*
> the documentation should start with the easiest way to get up and running without any advanced features. the product needs a much lower barrier to entry. there are also some things which could be solved in hotchocolate and strawberry shake itself to bootstrap faster.

*Daniel Gut  8 days ago*
> a PCF starter example probably should only add root types and no other types in the builder.

*Pascal  8 days ago*
> the resolver section really has to be reworked

*Adrian Frielinghaus*
> The hardest part of documentation is keeping it up to date as the code changes. I did find areas where the docs are out of date and no I can't think of examples but I do think improving documentation should start with making sure everything is still up to date. 

>Also sometimes when documentation seems to be a problem it is actually not a documentation problem but a code problem. For example I am always confised about V10.x and V11.x. they both seem to be under constant change and sometimes features percolate between the two. When versions are in flux like this it must be super hard to document the system. 

> Having 3 different ways to do everything is also a massive challenge for learning and adoption. 

## Possible Structure

- HotChocolate Concepts

- Graph Concepts
  - Schema
  - Object Types
  - Extending Object Types
  - Fields
  - Resolvers
  - Scalar Types
  - Enum Types
  - Union Types
  - Interface Types
  - Dataloaders 
  - Connections/ Pagination
  - Filtering / Sorting
  - Directives 
  - Relay 

- Guide to Pure Code First
  - Schema 
  - Defining Object Types
  - Extending Object Types
  - Using Interfaces and Unions
  - Defining Scalar Types
  - Defining Enum Types
  - Using Dataloaders
  - Connections/Pagination
  - Filtering / Sorting

> reconsider naming

- Guide to Code First
  - Schema
  - Defining Object Types
  - Extending Object Types
  - Using Interfaces and Unions
  - Defining Scalar Types
  - Defining Enum Types
  - Using Dataloaders
  - Connections/Pagination
  - Filtering / Sorting

> reconsider naming
- Guide to Schema First
  - Schema
  - Defining Object Types
  - Extending Object Types
  - Using Interfaces and Unions
  - Defining Scalar Types
  - Defining Enum Types
  - Using Dataloaders
  - Connections/Pagination
  - Filtering / Sorting

- Principals and Architecture
  - Type System 
       - Descriptor
       - Definition 
       - Type 
       - Node 
  - Schema Construction & Organization 
  - Lifecycle, Deployment and Release Management
  - Folder and Project Structure / Code Organization
      - PCF
      - CF
      - SF
  - Execution Piplines

## Ideas for other Ressources
**Adrian Frielinghaus  8 days ago**
>Last comment on documentation is that if you want to make it easier to onboard new people I think the best way would be a Pluralsight course. 

**Daniel Gut some time ago**
> the new chillicream page may could make use of .net interactive : https://devblogs.microsoft.com/dotnet/net-interactive-is-here-net-notebooks-preview-2/

## Reference Documentation 
- https://angular.io/ 
- https://www.apollographql.com/docs/
- https://ant.design/components/button/
- https://relay.dev/docs/en/introduction-to-relay

**Comment by freever** [comment]
It seems like the big issue we need to solve is how to deal with the 3 approaches or "flavours". We are struggling to explain how to use HotChoc because we have to do it three different ways all the time. We have discussed resolving this in different ways but they all come with problems. 

The main idea seems to be that we should have 3 tabs or sections that explain exactly how each flavour does each thing and have separate API and guides sections that talk about how to do HotChoc generically without being flavour-specific. In other words we separate "what" HotChoc can do from "how" it is done. This makes logical sense but I don't think it makes it easy to learn HotChoc. Fundamentally, technical documentation needs to talk about what you can do and how you can do it in the same place. It's also very, very hard to write documentation abstractly without referring to code. 

So we are faced with a choice between talking about what and how together, which means we have to duplicate everything 3 times, or splitting the what and the how which will make it harder to understand. 

I'm new to GraphQL and to HotChoc so maybe I'm missing something fundamental here, but I don't understand why we need to give equal importance to each approach. In my noobness it seems like Schema-First is something you would do if you already have a huge schema and you want to start experimenting with exposing some of it in C#, Code First was the initial way we thought it would be best to start fresh in C#, and PCF is what we now think is the best approach after all the learnings from the past 2 years. So perhaps they aren't equal. Maybe there are different contexts or use cases that apply. 

I do get the feeling, reading between the lines of what is written and said in the community, that PCF is really what makes HotChoc different and exciting - and also what most leverages the power of .NET in the GraphQL context. If this is true then perhaps it gives us an opportunity to simplify the documentation. 

Instead of separating the what and how, we can build all the documentation using PCF as the reference approach, making everything simpler to understand. Then we just need a document explaining why you might want to use Code-First or Schema-First instead of the preferred approach, and very small technical reference docs showing the flavour-specific implementation of the PCF implementation shown in the documentation. 

The main idea here is that perhaps we should reconsider giving equal weight to all three approaches. Pick a favourite and build the documentation around it, and link off to flavour-specific translations.

**Comment by arif-hanif** [comment]
I would like to throw some additional reference docs in that are really good https://hasura.io/docs/1.0/graphql/manual/index.html
https://lighthouse-php.com/4.12/getting-started/installation.html

**Comment by damikun** [comment]
Hey isn't there in current documentation  (https://hotchocolate.io/docs/schema-object-type) missing return type (void) in all override methods?? In Vs-code this will not get compiled...

![return type](https://user-images.githubusercontent.com/54806834/82822266-c92a3380-9ea5-11ea-8db3-73799a9fc23e.PNG)
