### ISSUE TITLE
Suggestion for a Complimentary GraphQL Client for ASP.NET Core Blazor

### ISSUE THREAD

**Issue by geekox86** [ChilliCream/hotchocolate#1570]
Greetings gentlemen,

I would like to suggest creating a new GraphQL client to complement this awesome GraphQL server framework. The timing of this suggestion is related to introduction of ASP.NET Core Blazor. As web developers, we are used to use something like Apollo Client to communicate with out HotChocolate Server in JavaScript world. However, the world is changing now for a full-stack pure .NET implementations for both client and server. Hence, the need for an awesome client. There may be some existing GraphQL clients, and I have not throughly looked at all of them; but the trust in your framework quality is pushing me to ask for a complimentary client with similar quality as well.

What do you guys think?

**Comment by PascalSenn** [comment]
@geekox86  There is already one. And it is awesome! ;)
Check it out here, it available in 11 previews. At the moment there is a massive PR from @michaelstaib  in the works that will further improve it :) 

It is a graphql client that generates c# types for your queries, mutation or subscriptions. Like actuall C# types
The tooling downloads the schema file so. The client is actually generated from this downloaded file.
You only need to have the server running when you update the schema file.
So only when you change the schema :)

It comes with tooling so that you really only have to set it up once and then the client is generated on every build.
You just have to do this:

You just have to do this:
1) add reference to StrawberryShake in project file
     currently the newest version is 11.0.0-preview.84
2) install the tool in the project folder
   ` dotnet tool install strawberryshake.tools --version 11.0.0-preview.84`
3) initialize the project
`dotnet graphql init <<graphqlendpoint>> -p <<path fot the client>> -n <<name of the client>>`
e.g.
` dotnet graphql init  http://localhost:60004/graphql -p ./Clients/MyClient -n MyClient`
4) add a query file `Queries.graphql` to the folder /Clients/MyClient
5) register generated client and http client in di
6) build and enjoy. 

more info you find in the blog post, the github repo or on slack
You can join here: 
https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q

Check it out:
https://chillicream.com/blog/2019/11/25/strawberry-shake_2

**Comment by geekox86** [comment]
@PascalSenn this is actually fantastic news :-)

I will definitely a try and provide feedback.

I am very interested on the caching aspects of the client.
What are the caching strategies available?

I may need to sneak into the source code a bit.

**Comment by PascalSenn** [comment]
@geekox86  I could be wrong but I don't think there are any implemented yet. 
But this is definitely a question for @michaelstaib

**Comment by michaelstaib** [comment]
it is still early. The store api is not yet in ... we are currently focusing on the pipeline api and the generators. after this is in we will focus on state management.

**Comment by michaelstaib** [comment]
I am closing this issue

**Comment by michaelstaib** [comment]
I am giving an online talk about this next Friday ... get registered if you are interested:
https://www.meetup.com/DotNetIasi/events/269455344/
