### ISSUE TITLE
Code-first generates CLR strings as IDs in schema

### ISSUE THREAD

**Issue by jchapman127** [ChilliCream/hotchocolate#1588]
In 10.4 by default all `string` properties on schema objects are bound to `ID` in GraphQL schema when using code-first approach.

I managed to fix it by adding `.BindClrType<string, StringType>()` to my schema definition.

**Comment by michaelstaib** [comment]
It is not by default. With all version 10.x schemas the first binding defines to what a clr type is bound. We have changed that behavior in version 11 where we now have to binding types.

**Comment by michaelstaib** [comment]
The solution with `.BindClrType<string, StringType>()` is a correct remedy to your issue.

**Comment by jchapman127** [comment]
I have another project using 10.3.x where this doesn't happen. If I understood you correctly, are you saying that the current (10.x) behaviour is sensitive to ordering of properties/types when discovering them for a schema?

**Comment by michaelstaib** [comment]
It also happens in 10.3. It just depends on which type declaration is found first. That is why we did a fundamental change with 11 on this. 

> If I understood you correctly, are you saying that the current (10.x) behaviour is sensitive to ordering of properties/types when discovering them for a schema?

Yes, and this is a design flaw of 10.x

We however changed that already for 11.0.0. With the current previews you will not have this issue.... however, I would stay on 10 for now and for bind it like you did since we are in the middle of big features that are coming into 11 and with them instabilities.

Also just as a side note, these issue with the type binding only happen when there are two scalars that are based on the same .net type.

**Comment by jchapman127** [comment]
Great explanation, thanks. I eagerly await version 11!
