### ISSUE TITLE
Improve Resolver API Discussion

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1608]
We have started a discussion on improving the resolver API on Slack and removing 
inconsistencies.

At the moment resolvers inferred from a member have a lot of injection capabilities where all the wiring is done by the resolver compiler:

```
descriptor
    .Field(t => t.MyFunc(default, default));
```

Where one defines a resolver through the `Resolver(...)` descriptor all the bindings have to be done by hand:

```
descriptor
    .Field("foo")
    .Resolver(t => t.MyFunc(t.Argument<string>("foo"), t.Service<Baz>()));
```

Another issue is that once the field configuration is started we do not pass down the field descriptor as generic which leads to issues where we cannot captor the actual source type.

In order to mitigate this we do think that deprecating the old resolver API is warranted.

deprecate:
```
descriptor
    .Resolver(t => t.Parent<Foo>().Foo)
```

And we would introduce a new api that also better aligns with the `Subscribe` resolver. The new `ResolveWith` descriptor would allow for all the injection capabilities that `Field` at the moment has. 

new:
```
descriptor
    .Field("name")
    .ResolveWith(t => t.Member)
descriptor
    .Field("name")
    .Resolve(context => t.Parent.Foo)
```

Also with this change we would add another descriptor interface for the field that caries the source type.

`IObjectFieldDescriptor<T>` would also implement `IObjectFieldDescriptor` so that existing APIs will have no compatibility issue with that.

**Comment by benmccallum** [comment]
Been chatting with Michael about this and I have a use case. Essentially I want to be able to register my type as a node and in passing a lambda of the property of my `id`, I want to also setup a `dbId` field that just returns my internal id (int, string, guid, etc. from the DB).

I tried this:
```c#
public static INodeResolverDescriptor<T, TId> AsNodeUsing<T, TId>(this IObjectTypeDescriptor<T> descriptor,
    Expression<Func<T, TId>> propertyOrMethod)
{
    // Add dbId which should just return the internal id as is
    // both have issues
    descriptor.Field("dbId").Resolver(propertyOrMethod);
    descriptor.Field(propertyOrMethod).Name("dbId");

    // Call standard stuff
    return descriptor.AsNode().IdField(propertyOrMethod);
}

// So that instead of 
descriptor.AsNode().IdField(u => u.Id);

// I could do:
descriptor.AsNodeUsing(u => u.Id);
// and get `id` and `dbId` fields
```

But as Michael pointed out in our discussion, `propertyOrMethod` is used internall in HC as an identifier, so that field meta can be retrieved and extended on later.

So what I need I believe is this proposal, so I could do `descriptor.Field("dbId").ResolveWith(propertyOrMethod)` and it'd be happy days!

**Comment by michaelstaib** [comment]
#1892
