### ISSUE TITLE
Authorization Middleware Refactoring

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1649]
The authorization middleware has become quite complex with handling cases for the old ASP.NET and for ASP.NET Core. 

Since we do no longer provide a ASP.NET middleware we should fully embrace the policy approach and remove all the other cases.

**Comment by nguyenquyhy** [comment]
Currently Authorize attribute does not support multiple schemes or Policy schemes. May I know if this work would include Schemes support?

I am thinking of forking to implement this but I don't want to duplicate the same effort.

**Comment by thomastvedt** [comment]
> I am thinking of forking to implement this but I don't want to duplicate the same effort.

I'm interested if you decide to do this ;)

**Comment by Alxandr** [comment]
Also, one more not. I think it would be better if it was possible to do this like they do with endpoint routing. That instead of having authorize be a field middleware, any field that requires authorization adds some metadata to the entire request, and then authorization can be run once, instead of per field. I'm not sure how to go about making something like that though.

**Comment by michaelstaib** [comment]
@Alxandr yes that sounds good. I will set a meeting up for next week where we can hash out the details.
