### ISSUE TITLE
Error when specifying a dynamic list type

### ISSUE THREAD

**Issue by kamsar** [ChilliCream/hotchocolate#1689]
**Describe the bug**
I'm trying to specify a field that is a list of a dynamic graph type that does not have a corresponding C# type. In my particular case the graph type needs to dynamically align with a schema defined in a database.

This worked well for fields until I tried to define a list of this dynamic type, which throws this exception:

```
Unable to cast object of type 'HotChocolate.Types.ListType' to type 'HotChocolate.Types.TypeSystemObjectBase'.
```

I might just be doing it wrong?

**To Reproduce**

```csharp
[Fact]
public async Task BreakStuff()
{
    var schema = SchemaBuilder.New()
        .AddQueryType(new ObjectType((descriptor) =>
        {
            descriptor
            .Name("Query")
            .Field("hello")
            // the problem - this won't work but .Type<ListType<StringType>>() does
            // (in actual implementation 'new StringType()' is a specific instance of ObjectType so I can't use the generic version)
            .Type(new ListType(new StringType()));
        }))
        .Create();

    var executor = schema.MakeExecutable();

    await executor.ExecuteAsync(QueryRequestBuilder.Create("{ hello }"), CancellationToken.None);
}
```

**Expected behavior**

```
type Query {
  hello: [String]
}
```

**Desktop (please complete the following information):**
 - OS: Windows 10/.NET Core 3.1.202
 - Version: latest master

**Comment by kamsar** [comment]
I found a workaround by declaring the type as 
```
.Type(new ListTypeNode(new NamedTypeNode("ExplicitNameOfGraphType")))
```

**Comment by Beamed** [comment]
For that workaround, do you have to provide the descriptor of that type elsewhere? Encountering the same issue.

**Comment by kamsar** [comment]
Yes, the type must be added to the schema elsewhere

________________________________

**Comment by Beamed** [comment]
Hm, that doesn't seem to work:
```csharp
                        schemaConfig.RegisterType(objectType);
                        var listType = new ListTypeNode(new NamedTypeNode(kv.Key));//kv.Key is the name of the object type
                        newDescriptor.Type(listType);
```
Leads to an error that it can't find the type. :(

**Comment by michaelstaib** [comment]
This really creates a new type in the type system `.Type(new ListType(new StringType()));`. In order to build dynamic schemas it is better to use the syntax type reference.

What also can be done is to use the SDL syntax tree to define a schema. I know this is a bit clunky but also a way you can di it. I will create a new issue that will analyze dynamic schemas more to find a better API to describe them. 

I will close this issue and we will have a look at the topic when we start planing on version 12.

**Comment by Beamed** [comment]
Fwiw, my issue here was that you can't define types later with their own descriptors - you have to have created the type, on the schema, before you set a ListTypeNode(name) on the schema. That resolved my issue with the workaround, but it appears the underlying issue persists.

**Comment by michaelstaib** [comment]
What issue do you mean?

**Comment by Beamed** [comment]
new ListType(new ObjectType(descriptor => \\..)); not working out of the box.

**Comment by michaelstaib** [comment]
It is actually working out of the box... but new ObjectType() creates a new type instance meaning if you do it two times and mean the same time it will lead to a type collision.

But if you use the lower level api with the new type interceptor things like that are very well possible.

**Comment by Beamed** [comment]
Sorry, I want to clarify this point (thank you for responding, btw! :) ) - are you saying that you can't replicate the issue highlighted here, or that new ListType(new ObjectType()) is not intended to work, and newer coming APIs make it obsolete? This distinction is important, imho, because the API specs for List Type strongly imply this **should** work, and is critical for dynamically generated schemas (not backed by .net core types)
