### ISSUE TITLE
How do to search instantiated Object

### ISSUE THREAD

**Issue by hello-hyh** [ChilliCream/hotchocolate#169]
Hi,I want use a instantiated object to create Schema by code first, but as if cannot call  *RegisterQueryType*   method to get success result. code following
`  Query query = new Query()
     {
        head = "head"
      };`
`var schme = Schema.Create(x => x.RegisterQueryType(query));`  
POCO following  
`public class Query : ObjectType`
  `{`
   `public string head { get; set; }`
   `public string Querys() => "hello";`
   `}`
Error message  
`Error: Query fields must be an object with field names as keys or a function which returns such an object`
Thanks.

**Comment by michaelstaib** [comment]
Hi,I want use a instantiated object to create Schema by code first, but as if cannot call RegisterQueryType method to get success result. code following
Query query = new Query() { head = "head" };
var schme = Schema.Create(x => x.RegisterQueryType(query));
POCO following
public class Query : ObjectType
{
public string head { get; set; }
public string Querys() => "hello";
}
Error message
Error: Query fields must be an object with field names as keys or a function which returns such an object
Thanks.

Hi,

I can see the issue with your example. We will soon invest some more time to make our documentation better.

There are basically two ways to work with code first. You can opt for POCO classes which are plain .net classes that do not inherit from any hot chocolate classes.
So in your case the `Query` class would look something like this:

```csharp
public class Query
{
    public string Head { get; set; }
    public string GetQuery() => "hello";
}
```

The following class would result in the following schema

```graphql
type Query {
  head: String
  query: String
}
```

In order to create a schema with your POCO class do the following:

```csharp
var schema = Schema.Create(c => {
    c.RegisterQueryType<Query>();
})
```

The problem with the very clean POCO approach is that we currently cannot infer non-null reference types due to the fact that currently all reference types in .net are nullable.
In order to describe your schema in a richer way and still just use c# you can use the type objects. In this case I could create a another class that is called QueryType:

```csharp
public class QueryType
    : ObjectType<Query>
{
    protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
    {
        descriptor.Field(t => t.GetQuery())
            .Type<NonNullType<StringType>>();
    }
}
```

The `QueryType` represents a native schema type object. You could compare it to System.Type. 
In general using schema types like `ObjectType`, `InterfaceType` will give you more control over your exposed schema than you have with only POCO types.
So, in your case it defines that the POCO `Query` is an object type and uses the `Configure` method to define that `GetQuery` is a non-null `String` field.
By default we will try to automatically infer all your fields, their types and how to resolve them.

Instead of query you would now register the `QueryType` with the schema:

```csharp
var schema = Schema.Create(c => {
    c.RegisterQueryType<QueryType>();
})
```

Now the graphql schema would like the following:

```graphql
type Query {
  head: String
  query: String!
}
```

You could also now use the `QueryType` descriptor to add fields that you do not have in your poco or add more functionallity to a field of your poco:

```csharp
 public class QueryType
    : ObjectType<Query>
{
    protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
    {
        descriptor.Field(t => t.GetQuery())
            .Type<NonNullType<StringType>>();

        // add additional fields
        descriptor.Field("newfield")
            .Resolver(() => "hello world");

        // redefine functionallity of field
        descriptor.Field(t => t.Head)
            .Argument("a", a => a.Type<NonNullType<StringType>>())
            .Type<NonNullType<StringType>>()
            .Resolver(c => (c.Parent<Query>().Head ?? "") + c.Argument<string>("a"));
    }
}
```

```graphql
type Query {
  head(a: String!): String
  query: String!
  newfield: String
}
```

You can also exclude fields of your POCO by matking them as ignored:

```csharp
descriptor.Field(t => t.GetQuery()).Ignore();
```

Also, you can use the non generic api and create your api without a poco:

```csharp
 public class QueryType
    : ObjectType
{
    protected override void Configure(IObjectTypeDescriptor descriptor)
    {
        descriptor.Field("query")
            .Type<NonNullType<StringType>>()
            .Resolver(() => "hello");

        descriptor.Field("head")
            .Type<NonNullType<StringType>>()
            .Resolver(() => "world");
    }
}
```

```graphql
type Query {
  head: String
  query: String!
}
```

If you want to get started very quickly you can use our dotnet cli templates:

```bash
dotnet new -i HotChocolate.Templates.Server
dotent new graphql-server
```

There is also our star wars example:

```bash
dotnet new -i HotChocolate.Templates.StarWars
dotent new starwars
```

I hope this is going to help you and don't hesitate to get back to us if not.

Kind regards,

Michael

**Comment by michaelstaib** [comment]
Just re-read your question. So, you want to register an instantiated query type. What is your intention with that. The idea to pass in an instantiated type is so you have a short-hand configuration syntax like the following:

```csharp
var schema = Schema.Create(c => {
    c.RegisterQueryType(new ObjectType<Foo>(d => d.Name("Bar")));
})
```

Do you want a specific query instance during execution?


If so this can be done like the following:

```csharp

schema.Execute("{ head }", c => c.InitialValue = new Query());

```
