### ISSUE TITLE
Ability to hide fields from both schema download and querying

### ISSUE THREAD

**Issue by mattdurham** [ChilliCream/hotchocolate#1743]
We have a set of licenses that control what a user can do/see. We have added authorize attributes so that they can't read the values but they can still see them in the schema. In an ideal world we can add a filter or even some sort of rewriter that allows use to filter out the fields on query and introspection similar to Authorize, or conversely make Authorize == false hide the fields . I tried looking at some of the Descriptors and Rewriters but couldnt find anything that met the goal.

**Comment by michaelstaib** [comment]
Do you mean you want to hide fields from the schema?

**Comment by mattdurham** [comment]
Yes, conditionally based on the user's information.

**Comment by michaelstaib** [comment]
You would not actually do that with GraphQL since this would mean instability to tooling like relay or our own strawberryshake or even playground and others.

The GraphQL way here is to have partial results, meaning to not return data that the user is not allowed to.

here is a good talk from Dan Schafer one of the three devs who created GraphQL. He discusses how you would do Authorization in GraphQL.

We have made this even easier with our authorization directive.

https://www.youtube.com/watch?v=etax3aEe2dA&amp=&feature=emb_rel_end

**Comment by michaelstaib** [comment]
If you want to host different schemas, that will be possible with version 11. But this will be complete schemas although you will be possible to switch between schemas based on a various set on information.

**Comment by michaelstaib** [comment]
I am closing this issue.
