### ISSUE TITLE
Authorization Middleware can never return NotAuthenticated error code

### ISSUE THREAD

**Issue by hyphmongo** [ChilliCream/hotchocolate#1762]
If I have a policy based directive attached to my resolver fields and I'm passing an expired/invalid JWT version `10.4.0` would return a `ErrorCodes.Authentication.NotAuthenticated` error code.

A change was made in this commit https://github.com/ChilliCream/hotchocolate/commit/2e8b7b282bc95c4f01605cdaf1c9e9b0959f5194 which means from `10.4.1` onwards this scenario will return a `ErrorCodes.Authentication.NotAuthorized` error code. 

```
if (NeedsPolicyValidation(directive))
{
  authenticated = allowed = true;
}
else
{
  authenticated = allowed = p.Identities.Any(t => t.IsAuthenticated);
}
```

Authenticated will be always set to true, and if the policy returns false, the ternary in `SetCode` in the `ErrorBuilder` will always set the `ErrorCodes.Authentication.NotAuthorized` error code.

I think setting the `authenticated` variable should be independent of `allowed` so that if `NeedsPolicyValidation` returns true, allowed would be true but if there are no authenticated identities on the principal then authenticated should be set to false. So then we can still reach the correct error code.

**Comment by michaelstaib** [comment]
This was intentionally done so that in case you have a policy you also can handle the authenticated state in the policy. This allows you to for instance allow people to query the schema via introspection while denying people access to non-introspection fields.

So, basically we are delegating responsibility for the authenticated check to policy.

This in turn lead to nod being able to distinct between not authorized and not authenticated. With version 11 we might remove the not-authenticated code entirely. 

We also could make this optional, I am not sure at this moment and we will revisit this when we start work on the middleware.
