### ISSUE TITLE
LongType truncate value

### ISSUE THREAD

**Issue by sergeyshaykhullin** [ChilliCream/hotchocolate#1846]
**Describe the bug**
I tried to return long value from resolver, but got truncated value

**To Reproduce**
1. Create field:
```cs
descriptor.Field("longField")
	.Type<LongType>()
        // .Resolver(551085521103355905);
	.Resolver(context => 551085521103355905);
```
2. Query field:
```gql
{
  longField
}
```
3. Result:
![image](https://user-images.githubusercontent.com/46970457/80709181-8c149080-8af5-11ea-9555-a658a09fbbf3.png)

**Expected behavior**
Long supports longer values
![image](https://user-images.githubusercontent.com/46970457/80709228-9f276080-8af5-11ea-9da5-3fbb5d90a364.png)

**Desktop (please complete the following information):**
 - HC: 10.4.2

**Comment by sergeyshaykhullin** [comment]
Also, tested with value` 551089232914251777`, but got `551089232914251800`

**Comment by sergeyshaykhullin** [comment]
Also 2, input field value with `551085521103355905` and `551089232914251777` deserialized correctly, without truncation

**Comment by michaelstaib** [comment]
strange, will write a test ...

**Comment by sergeyshaykhullin** [comment]
@michaelstaib 10.4.3 released, this issue isn't resolved. Still getting truncated values

**Comment by michaelstaib** [comment]
It was not yet fixed

**Comment by michaelstaib** [comment]
We fix a stitching bug with 10.4.3

**Comment by michaelstaib** [comment]
We will move everything else to 10.4.4

**Comment by michaelstaib** [comment]
Is this still an issue @sergeyshaykhullin?

**Comment by sergeyshaykhullin** [comment]
@michaelstaib Yes

![image](https://user-images.githubusercontent.com/46970457/108518013-2a6a2080-72d9-11eb-91e5-3f35f182a78c.png)

**Comment by PascalSenn** [comment]
@sergeyshaykhullin  
Found it.
The problem is not HotChocolate:
<img width="381" alt="image" src="https://user-images.githubusercontent.com/14233220/111229343-05ba4d80-85e6-11eb-9c81-f6e980ceb197.png">
It's Javascript:
<img width="289" alt="image" src="https://user-images.githubusercontent.com/14233220/111229370-12d73c80-85e6-11eb-9509-5053e6411a30.png">

I can see this issue in BCP but also in Altair:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/14233220/111229407-25517600-85e6-11eb-8262-b844914d1409.png">
GraphIQL
<img width="348" alt="image" src="https://user-images.githubusercontent.com/14233220/111229694-a3ae1800-85e6-11eb-81ab-6d3fa3f88c46.png">
Playground
<img width="448" alt="image" src="https://user-images.githubusercontent.com/14233220/111229881-ff78a100-85e6-11eb-91ca-4ff66b64c2fd.png">

And even the json visualiser of Chrome:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/14233220/111229916-10291700-85e7-11eb-9bdd-5c187910a69c.png">

No idea if we can fix that in the frontend. But maybe @rstaib  or @fredericbirke  have an idea

**Comment by sergeyshaykhullin** [comment]
Omg 😅

**Comment by rstaib** [comment]
String value 😄 or BigInt

**Comment by rstaib** [comment]
I will see what we can do in BCP 👍

**Comment by glen-84** [comment]
@PascalSenn

The problem _is_ actually Hot Chocolate, since there is [no interoperable support for 64-bit integers in JSON](https://news.ycombinator.com/item?id=12858613), and HC should instead serialize longs as strings.

Should I open an issue for this?

**Comment by michaelstaib** [comment]
No, that is also not what the spec text says. 

> This specification allows implementations to set limits on the range
   and precision of numbers accepted.  Since software that implements
   IEEE 754-2008 binary64 (double precision) numbers [[IEEE754](https://www.rfc-editor.org/rfc/rfc7159#ref-IEEE754)] is
   generally available and widely used, good interoperability can be
   achieved by implementations that expect no more precision or range
   than these provide, in the sense that implementations will
   approximate JSON numbers within the expected precision.  A JSON
   number such as 1E400 or 3.141592653589793238462643383279 may indicate
   potential interoperability problems, since it suggests that the
   software that created it expects receiving software to have greater
   capabilities for numeric magnitude and precision than is widely
   available.

>    Note that when such software is used, numbers that are integers and
   are in the range [-(2**53)+1, (2**53)-1] are interoperable in the
   sense that implementations will agree exactly on their numeric
   values.

First of, it says may. There is no must in the spec that prohibits use of this. In general you can take steps to parse longs correctly in JS.

So, no, we are not reopening this.
