### ISSUE TITLE
[Experimental]Input Union

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#1880]
https://github.com/graphql/graphql-spec/blob/master/rfcs/InputUnion.md

**Comment by syaylev-minbox** [comment]
Hi! Do you have any estimates on this feature ?

**Comment by PascalSenn** [comment]
@syaylev-minbox  this feature will probably not make it into the graphql-spec. So i would not wait for it.

**Comment by syaylev-minbox** [comment]
May be do you have any ideas how could implement it by myself? How could I simulate inheritance for input parameters ? It would be nice if I had any ad-hoc or temporary solution on this.

**Comment by syaylev-minbox** [comment]
Just for history, I hope this would be useful for those who want to implement this option by them self. This is an idea, not recipe.

I'm trying to implement option 1 (explicit __typename Discriminator field) from that article, so fronted client can pass input parameters with the same structure as he\she got with output types. I believe this would be more comfortable to use it on client side, than option 7 (tagged union). But this idea can help you to implement option 7 too.

1. Invent InheritanceInputType that would deceive HotChocolate with it's ParseLiteral override:

```
public class InheritanceInputObjectType<T> : InputObjectType<T>
{
    public override object ParseLiteral(IValueNode valueSyntax, bool withDefaults = true)
    {
        var typeName = ((List<ObjectFieldNode>)valueSyntax.Value).First(f => f.Name.Value == "__typename").Value.Value + "Input";

        // invent by yourself how would you pass CatInputType.Instance (of type InputObjectType<Cat>) here
        InputObjectType realType;
        if (typeName == CatInputType.Instance.Name.Value)
            realType = CatInputType.Instance;
        if (typeName == DogInputType.Instance.Name.Value)
            realType = DogInputType.Instance;
        else
            throw new InvalidOperationException();

        var value = realType.ParseLiteral(valueSyntax, withDefaults);

        var dictToObjConverter = new DictionaryToObjectConverter(Converter);

        var result = dictToObjConverter.Convert(value, realType.RuntimeType);

        // compile-time type in mutation stays AnimalBase, but run-time type is specific animal
        return result;
    }
}
```

2. Add this type and all descendants to your schema 
```
IRequestExecutor executable = SchemaBuilder.New()
    .AddQueryType<ComplexQuery>()
    // by default registeration annotation-based type is hidden into HotChocolate.Configuration.SchemaTypeResolver line 52
    // but you can overtake this by registering type by yourself 
    .AddType< InheritanceInputObjectType<AnimalBase>>()
    // add all descendants here. In my case I will use reflection because I do not know all thees types at compile-time
    .AddType< InputObjectType<Cat> >()
    .AddType< InputObjectType<Dog> >()
```

3.1 Completely disable validation for input parameters. Copy-past HotChocolate.Validation.Rules.ValueVisitor, find method `Enter(ObjectFieldNode node, ...)`, `comment context.Errors.Add(...)` in else section (you can use wrapper patter + reflection to avoid code copy-pasting). See code [here](https://github.com/ChilliCream/hotchocolate/blob/c1eb36cf3542572372847c5e38f4bc349bc22bfa/src/HotChocolate/Core/src/Validation/Rules/ValueVisitor.cs#L239).

```
protected override ISyntaxVisitorAction Enter(ObjectFieldNode node, IDocumentValidatorContext context)
{
    if (context.Types.TryPeek(out IType type) &&
        type.NamedType() is InputObjectType it &&
        it.Fields.TryGetField(node.Name.Value, out InputField? field))
    {
        // omited
       ...
    }
    else
    {
        // here ->
        // context.Errors.Add(context.InputFieldDoesNotExist(node));
        return Skip;
    }
}
```

3.2 Now find the way to replace `ValueVisitor` in `[HotChocolateValidationServiceCollectionExtensions.AddValidationCore](https://github.com/ChilliCream/hotchocolate/blob/c1eb36cf3542572372847c5e38f4bc349bc22bfa/src/HotChocolate/Core/src/Validation/Extensions/ValidationServiceCollectionExtensions.cs#L36)` . Seems that currently there is no way except copy-pasting of methods `static AddGraphQL` and `static AddValidation`

You can try to rewrite validation of input value in more complicated way. You can validate it according to __typename field.

If client will try to pass extra fields that are not part of specific animal (wings count for __typename=cat) then you get exception later when InheritanceInputObjectType trys to `realType.ParseLiteral`. So validation disabling is the price I can pay today.

That is it. Add reflection based on your preference. 

4. Now you can create mutation using AnimalBase `public int ChangeAnimal(AnimalBase animal) { ... }`

There is still a bunch of problems on client side. In gql schema there would be no inheritance between AnimalBase, Cat and Dog types. And output types for Cat will have __typename="Cat" , but input type will have __typename="CatInput" and this can break type-checking in typescript. But this could be solved with several trade-offs.

I hope this idea might be useful for HC dev team, because it shows one of usecases of customizing this lib.

**Comment by michaelstaib** [comment]
I am closing this issue since the input union was abandoned by the spec. It will not become part of the GraphQL spec. The current thinking in the GraphQL working group is that the one-of proposal will become part of the spec and offer functionality for input unions. We will add support for this with the September release.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/issues/3784
