### ISSUE TITLE
Query attribute order should not matter

### ISSUE THREAD

**Issue by jsheely** [ChilliCream/hotchocolate#1939]
**Describe the bug**
Currently when attribute decorating a query the order of the attributes must be in this order or it does not apply the filters
```
[UsePaging]
[UseFiltering]
[UseSorting]
public IQueryable<Person> GetPeople([Service] DataContext dataContext) =>
            dataContext.People;
```

If you move [UseSorting] to the middle then sorting won't apply. If [UseFiltering] is the last option then it won't apply filters.

Based on the iQueryable they should probably be able to be applied dynamically in any order I believe without causing any problems

**Comment by michaelstaib** [comment]
This is actually a main feature and helps to bring in middleware semantic... what you can do with the attributes is form a pluggable pipeline. 

We have described the resolver pipeline in this blog post:
https://dev.to/michaelstaib/get-started-with-hot-chocolate-and-entity-framework-e9i

I will close this issue since this is a fundamental of Hot Chocolate.
