### ISSUE TITLE
ASPNetClassic Authorization Error When Accessing Authorized Resource

### ISSUE THREAD

**Issue by DarrenLouw** [ChilliCream/hotchocolate#2088]
**Describe the bug**
In my AspNet Classic Web project which is hosting HotChocolate as a middleware using OWIN,
When using ASPnetClassic Authorization's [Authorize] attribute on a class or property, an unexpected error is returned in the response when accessing the authorized class/property during runtime.

Error Message: 
**Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure \"HotChocolate.AspNetCore.Authorization.Properties.AuthResources.resources\" was correctly embedded or linked into assembly \"HotChocolate.AspNetClassic.Authorization\" at compile time, or that all the satellite assemblies required are loadable and fully signed.**

Stack Trace:    
at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)\r\n   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)\r\n   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)\r\n   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)\r\n   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)\r\n   at HotChocolate.AspNetCore.Authorization.Properties.AuthResources.get_AuthorizeMiddleware_NotAuthorized() in d:\\a\\1\\s\\src\\Server\\AspNetCore.Authorization\\Properties\\AuthResources.Designer.cs:line 77\r\n   at HotChocolate.AspNetClassic.Authorization.AuthorizeMiddleware.<InvokeAsync>d__2.MoveNext() in d:\\a\\1\\s\\src\\Server\\AspNetCore.Authorization\\AuthorizeMiddleware.cs:line 74\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at HotChocolate.Execution.ExecutionStrategyBase.<ExecuteMiddlewareAsync>d__10.MoveNext() in d:\\a\\1\\s\\src\\Core\\Core\\Execution\\ExecutionStrategyBase.Resolver.cs:line 40

**To Reproduce**

1. Create an empty ASP.Net web project (Mine is using classic .net framework 4.7.2)
2. Use these packages: 

- Microsoft.OWIN.Host.SystemWeb
- Microsoft.OWIN.Security.Jwt (My choice of authentication is JWT bearer tokens)
- HotChocolate ASPNetClassic

3. Add the attached OWIN Startup.cs file to the project:
[Startup.zip](https://github.com/ChilliCream/hotchocolate/files/4836756/Startup.zip)

4. Host the app
5. Send this graphQL query to the server:
`{
    hello
}`

**Expected behavior**
It is supposed to check if the client is authenticated or not and respond accordingly.
but instead you get the following response from the server:
![image](https://user-images.githubusercontent.com/43771950/85854436-afd21b00-b7b4-11ea-830d-105348a3b682.png)

**Desktop:**
 - OS: Windows 10
 - Version 1809

**Additional context**
Even without my JWT authentication middleware setup at all, it still gives the same output.
I've tried this with Hotchocolate Pure Code First and normal Code First. Both have the same result.

**Comment by DarrenLouw** [comment]
Hi, I found this stack overflow issue regarding the error i'm getting.
https://stackoverflow.com/questions/2058441/could-not-find-any-resources-appropriate-for-the-specified-culture-or-the-neutra

It says that it could simply just be a namespace referencing issue.
I noticed that the error mentions "HotChocolate.AspNetCore.Authorization". But this is aspnet classic hotchocolate, is that possibly the issue?

I'd like to look into this or even try to fix it myself, where can I get started developing on this aspnet classic hotchocolate package? Any pointers for starting out? I'm quite desperate to fix this.

**Comment by DarrenLouw** [comment]
@michaelstaib Any updates on this?

**Comment by Asshiah** [comment]
I have the exact same issue

**Comment by KerVitarLaeda** [comment]
I have got the same issue. Asp.net classic web api application. I think this is because Authorization library use same code for .net core & .net classic both via preprocessor dirictives. But resources are .net core only.
@DarrenLouw, Do you have any workarounds?
Thanks in advance.

**Comment by Asshiah** [comment]
As the version 11.0 is right around the corner, the team annonced they would not provide any fixes for the Asp.Net classic 10 version anymore. All efforts to support the OWIN pipeline used in Asp.Net classic were stopped with version 11.0. This is understandable as only a few people like us are still using the classic framework for new projects (due to enterprise mandatory guidelines or whatever).

In order to use it with Asp.Net classic, I had to get the Authorization part from the sources (versions 10.5.3) and recompile it directly after changing the name of some extension methods and the namespace in order to not have a conflict with the official package loaded automatically when using HotChocolate.AspNetClassic package. I also removed the Asp.Net Core code altogether as well as the preprocessor directives. This way, the resources where found correctly and I don't have an error anymore.

But this mean using different methods and namespaces than the one documented.

The only real and good alternative I found was to not use an ASP.NET Classic Web API project to host my GraphQL endpoint but an Asp.Net Core (version 2.1 LTS or 2.2 at most: 3.0 and 3.1 LTS cannot run on .NET classic anymore) running on the .NET Framework classic 4.8 runtime. This way I was able to use all the project references and libraries I needed for my code to work with legacy .NET classic while being able to use the Asp.Net Core pipeline and all the official Asp.Net Core HotChocolate packages that do not encounter this issue. This theorically will also permit us to use the new 11.0 version of HotChocolate with the .NET Framework classic runtime when it will be available. 

I think this is the only real alternative in order to keep getting the good stuff while staying on .NET classic until we migrated or code base to .NET core (if it is even possible. I personally have to maintain a C++/CLI data access layer that cannot be migrated to .NET Core as is without a major overhaul of the code).

**Comment by DarrenLouw** [comment]
As @Asshiah stated, it is possibly happening because of a bug in the validation library.
However, ASPNet classic support no longer exists in 11.0.

Either we have to move to .NET Core.
Or if you are forced to integrate with .NET framework (Classic), you will more than likely need to find a different GraphQL technology that is compatible with your .NET framework version. Even if you fiind a way to resolve this bug, the .NET classic framework is no longer supported in future releases anyway, and you will be working on "orphaned" technology iif you stick with .NET Classic.
