### ISSUE TITLE
Type definition for query extension

### ISSUE THREAD

**Issue by ademchenko** [ChilliCream/hotchocolate#2163]
_**Question**_
Suppose, there are a root Query and its extension, for instance, ReviewQueries. We have to mark ReviewQueries with attribute [ExtendObjectType(Name = "Query")]. Suppose,  we also have QueryType where we define Query behavior and would like to also define ReviewQueriesType - that's a pretty often need to do that. It's unclear how to register that ReviewQueryType - it returns the error "HotChocolate.SchemaException: The name `Query` was already registered by another type. - Type: Query" on startup.

**Comment by PascalSenn** [comment]
@ademchenko  can you provide some code?

**Comment by Zero3** [comment]
@ademchenko @PascalSenn 

I believe I am having the same issue. I'm trying to dynamically add fields to the root Query type.

Simplified example code:

````
services.AddGraphQLSchema(schemaBuilder =>
{
	schemaBuilder.AddQueryType(descriptor =>
	{
		descriptor.Name("Query");
	});

	schemaBuilder.AddType(typeof(PartialQueryType1));
	schemaBuilder.AddType(typeof(PartialQueryType2));
});
````

The next step is to merge our partial query types into our empty `Query` type. As far as I understand, one is supposed to rename them to "Query" to do this, just like `[ExtendObjectType]` seems to do. But we can't use `[ExtendObjectType]` in this case, as we can't modify the partial query types. So one can attempt to do this dynamically like this instead:

````
public class PartialQueryObjectType : ObjectType<PartialQueryTypeBase>
{
	protected override void Configure(IObjectTypeDescriptor<PartialQueryTypeBase> descriptor)
	{
		descriptor.Name("Query");
	}
}

services.AddGraphQLSchema(schemaBuilder =>
{
	...
	schemaBuilder.AddType(typeof(PartialQueryObjectType));
});
````

But that leads to this exception:

````
HotChocolate.SchemaException: The name `Query` was already registered by another type. - Type: Query
````

**Comment by michaelstaib** [comment]
```
public class PartialQueryObjectType : ObjectTypeExtension<PartialQueryTypeBase>
{
	protected override void Configure(IObjectTypeDescriptor<PartialQueryTypeBase> descriptor)
	{
		descriptor.Name("Query");
	}
}
```

also have a look at our workshop:
https://github.com/ChilliCream/graphql-workshop

**Comment by michaelstaib** [comment]
I am closing this issue since type extensions are supported.

**Comment by Zero3** [comment]
@michaelstaib Thanks for your response.

I tried making such an `ObjectTypeExtension` class. It seems like it adds the specified generic type as an extension to the `Query` GraphQL type. I see that this could be useful if you are statically declaring each of your types.

In this case, however, the types are added *dynamically* using `schemaBuilder.AddType(type);` where `type` is a `System.Type` object. So for an `ObjectTypeExtension` to be useful in this case, it would have to be applied to all the dynamically added types. I tried creating both an `ObjectTypeExtension<PartialQueryTypeBase>` (to match the superclass of the dynamically added type) and an `ObjectTypeExtension<IPartialQueryType>` (to match an interface on the dynamically added classes), but they seem to attempt to add the generic types as new GraphQL types to `Query` instead of modifying the dynamically added types.

**Comment by michaelstaib** [comment]
Why do you not use the non-generic `ObjectTypeExtension`?

**Comment by Zero3** [comment]
@michaelstaib I tried, but it has no effect on the schema :(.

**Comment by michaelstaib** [comment]
can you post some repro?

**Comment by Zero3** [comment]
@michaelstaib I don't have one, but I found a workaround for using `ObjectTypeExtension<T>` for my use case (@ademchenko FYI):

````
services.AddGraphQLSchema(schemaBuilder =>
{
	schemaBuilder.AddQueryType(descriptor =>
	{
		descriptor.Name("Query");
	});
	
	foreach (Type partialQueryType in ...)
	{
		Type myObjectTypeExtensionType = typeof(MyObjectTypeExtension<>);
		Type myObjectTypeExtensionTypeGeneric = myObjectTypeExtensionType.MakeGenericType(partialQueryType);
		
		schemaBuilder.AddType(myObjectTypeExtensionTypeGeneric);
	}
});
````


````
public class MyObjectTypeExtension<T> : ObjectTypeExtension<T>
{
	protected override void Configure(IObjectTypeDescriptor<T> descriptor)
	{
		descriptor.Name("Query");
	}
}
````
