### ISSUE TITLE
Discussion: Branding

### ISSUE THREAD

**Issue by tomphilbin** [ChilliCream/hotchocolate#2232]
## Context

I spent several months at the start of this year assessing GraphQL frameworks and in my view Hot Chocolate should be the most adopted GraphQL framework in the .NET ecosystem. It is faster, more feature rich, better documented, better led by its maintainers and has a much more vibrant and engaged community than even its closest competitor.

Over the past few years I’ve worked in industries where brand is everything. Branding is what keeps some businesses the dominant force in their market for decades, even when their competitors have far better products or services.

I know that branding can be incredibly personal and it’s not my intention to criticise or attack any of the work that’s been done. I think Hot Chocolate is a really fun name, with some really great brand assets and merchandise. It also it fits really well with the other ChilliCream products such as Green Donut and Strawberry Shake. I do find that there are a few issues with the current naming however, that I believe could be negatively impacting adoption. 

## Analysis

To the uninitiated, the fragmentation of the product names can be off-putting. GraphQL is a daunting prospect to those seeking to adopt it for the first time, and making distinctions between products to make their role clear is important. The current product names are not obvious about the roles that they play which I believe could be contributing to abandonment—engineers giving up before they realise how great the framework is. 

Due to the brand names being physical products it can also be much harder to find useful documentation or StackOverflow links online. For example searching “hot chocolate subscriptions” gives thousands of results of online subscription services that deliver hot chocolate powders. Although this seems like a contrived example, searching for help with Hot Chocolate online is something that I’ve personally struggled with quite a lot.

At four syllables Hot Chocolate can sometimes be cumbersome to say, especially when referring to namespaces or having in-depth technical conversations. We also have the added strain that Hot Chocolate’s main competitor is called GraphQL.NET which could cause a lot of engineers to believe that it is an official package of the .NET platform. This means that we need to stand out even more in order to catch the eye of potential users with a catchy name and strong brand image. 

## Case Study: Apollo

Apollo is an eco-system of JavaScript packages for GraphQL that have easy to understand product names and also retain a strong overall brand image. “Apollo Server” is the server framework for building GraphQL APIs and “Apollo Client” is the JavaScript client for calling GraphQL APIs. Their codebase is easy to understand as packages are namespaced clearly, for example even to the uninitiated `apollo-server-cache-redis` is easy to follow.

Apollo has three syllables so it’s easy to say and remember and it can be used interchangeably to describe any of its packages (backend teams can simply say Apollo, referring to the server and front end teams the same, but referring to the client.)

## Proposal

Introducing Soprano: The GraphQL Platform for .NET!

The name Soprano is influenced from the musical connotation of C#, it’s easy to say and it’s easy to integrate existing functionality under. Hot Chocolate would become Soprano Server and Strawberry Shake (or Banana Cake Pop, I’m afraid I’m unsure 😅) would become Soprano Client. Other products and areas of functionality can be extracted, refactored or created under this name which will lead to much improved clarity. Namespaces could become some of these examples: `Saprano.Server`, `Soprano.Client`, `Soprano.DataLoaders`, `Soprano.Caching.Headers`, `Soprano.Caching.Redis`, `Soprano.PersistedQueries`, etc. Which would greatly improve the expressiveness of the overall platform: new and existing contributors can easily add and extend. 

Searching would be considerably improved as a “soprano” is an abstract musical concept which should be much easier to add technical words or phrases to in order to get help, without receiving spurious results.

A few months ago I bought the domain soprano.dev when I tried to build an opinionated C# code formatter which ultimately didn’t come to fruition—don’t ask! I will gladly donate this domain if the maintainers wish to adopt this proposal. Separate areas of the project could be subdomained or pathed, e.g https://client.soprano.dev or https://soprano.dev/client (I personally prefer the latter.)

I understand that this would be a massive undertaking, but I truly believe that it would ultimately improve several areas of the project that are key to successful mass adoption. 

It would be great to hear from the maintainers and the wider community to discuss this further!

**Comment by steveoh** [comment]
While I completely endorse the idea of name changes, soprano is just as random as hot chocolate in my opinion. I will agree about the abandonment based on names since I have not even looked at what the other dessert options do from chili cream mainly because of their names. 

I'm pretty sure this ship has sailed already though but I am curious to see what happens with this issue.

**Comment by tomphilbin** [comment]
Hey @steveoh, thanks so much for your thoughts! I can definitely relate with your experiences of avoiding the other dessert projects and not fully understanding how they fit in. 

With regards to the name: it’s definitely not meant to be meaningful 😄. More, it’s supposed to provide an umbrella term for the entire platform that can command brand affinity. Soprano is short, easy to say and can hook into an aesthetic through fonts, iconography, design, etc. in order to provide impact (although I’d avoid extending this to terminology/language.) I’m not saying that it’s the only name that's capable of this, I just think it’s a strong candidate.

Hopefully the brand ship has never completely sailed, as it’s really important to evolve over time.

**Comment by steveoh** [comment]
Again I agree. I typically do this before I name a project though... https://github.com/search?q=soprano&type=Repositories

**Comment by michaelstaib** [comment]
Hi @tomphilbin,

while in the beginning, it took time to get the name recognized the name is now established. We also will have a series of videos with Microsoft for Channel 9 which will push the platform further. 

I am closing this issue since for us this issue is settled.

**Comment by PascalSenn** [comment]
For me the main issue is the lack of documentation. At the moment only hotchocolate has good documentation. Strawberry Shake  (Client) has a few blog posts but not more. Marshmallow Pie (Schmea Registery) has zero documentation yet. Green Donut (Data Loaders) is deeply integrated withing HotChocolate and is usually not used separately and this can lead to confusion because the documentation does not make this clear. 

We are willing to invest a lot of time into the documentation once we are finished moving around things in the core. Writing documentation that you know will be out of date soon is something that does not make sense. 

I understand the problem when searching HotChocolate et al on google. Though this problem is usually solved by adding graphql to the search query. 

I think when people compare graphql frameworks they will find us and HotChocolate is a name that they will remember. When you search graphql .net we are on the first page.  

I think rebranding is always something to consider. But at the moment it would be too early to do. HotChocolate has some adoption and people could already have stumbled upon it. If we rebrand all the things we need new Domains, a new Slack (probably then Discord), new Merch, new Repositories, new everything. Apart from this beeing a ton of work i think we would loose adoption in shortterm. 
If you already are an established brand this is all a lot easier but it still has issues. ZEIT re-branded to Vercel last year, and i can still not remember the new name.

**Comment by tomphilbin** [comment]
Hey @PascalSenn thanks so much for the feedback, I really appreciate it!

I completely agree with your comments around the current documentation and I'm definitely willing to help out with that. I suppose I'm looking holistically at the HotChocolate platform after being a member of the community for almost a year now. It's still difficult to understand all of the constituent parts: even having read several times that Strawberry Shake is the client I still confuse it with Banana Cake Pop, Green Donut, Marshmallow Pie, etc. because it's not obvious or easy to remember. Even if a rebrand is unpalatable for the maintainers at this time, I feel that the platform would greatly benefit from a unification under the HotChocolate name, such as HotChocolate Client, HotChocolate Server, HotChocolate DataLoaders, etc.

I would have been really interested to see more of the community's thoughts on this as it would've provided some valuable feedback on the current branding. Does ChilliCream have any such feedback or has any market research been done to test the response to the brand?

Just as an interesting aside: when I Google "GraphQL .NET" HotChocolate doesn't appear until the third page for me. I know there's a huge amount of things that can impact this, but I'd be interested in the HotChocolate SEO insights to see which is the more common experience.

Perhaps you're right that now isn't the best time to raise this. I genuinely hope that I haven't caused any offence with this issue as I know that creative areas can be very personal.

**Comment by michaelstaib** [comment]
We had the discussion around this and have decided to go forward with the names that we chose. We will not do any rebranding, also not later. I think rebranding is a bad idea and wastes only time that we can use to bring this platform forward. We are growing at the moment at a faster pace than GraphQL .NET. Also with the new series of Channel 9 videos coming out we will get another push in October / November. I really do not see why we should change anything around this. I personally think once the new web site is out and the new documentation that any confusion will wash away.

**Comment by benmccallum** [comment]
I agree with the sentiment that this can be addressed by documentation and that changing now is near impossible. I think [this PR](https://github.com/ChilliCream/hotchocolate/pull/2244) will go a long way making a lot of things more obvious. Essentially the landing page for most people will list out all the parts of the platform upfront. 

I also think what would be cool with the documentation site/s when they land is what the nuxt community has recently done, by implementing a consistent theme and top left logo across all their disparate major plugins:
* https://tailwindcss.nuxtjs.org/
* https://pwa.nuxtjs.org/
* etc

They plan to take this one step further and make a "switcher", kinda like Google and Microsoft, etc. have to swap between Outlook, OneDrive, Word, etc.
![image](https://user-images.githubusercontent.com/157336/91643328-80e55900-ea32-11ea-86d7-187973e17856.png)

No reason we couldn't do that like ChilliCream / HotChocolate, etc. (even it is just pages in the same site).

**Comment by michaelstaib** [comment]
@rstaib

**Comment by rstaib** [comment]
I agree with the previous comments that re-branding is a bad idea and that it would consume an immense amount of time which we should use right now to get our platform ready. I think we can solve most of the mentioned issues with our [new website](https://chillicream.github.io/hotchocolate) which will come out with Version 11.

@PascalSenn Yeah Zeit is still in my mind and I don't even know what Vercel means. Also I found Zeit a pretty cool name; probably because I'm a german :-)

@benmccallum That's what we're doing on our [new site](https://chillicream.github.io/hotchocolate/docs/hotchocolate). However, there is always room for improvement 👍 

Also I agree with @PascalSenn that this is a high quality issue 👍 Thank you!
