### ISSUE TITLE
Does it go async?

### ISSUE THREAD

**Issue by savamas** [ChilliCream/hotchocolate#2320]
Hi! Our team have chosen Hot.Chocolate as a framework to develop our microservices. We got a issue. 
![Screenshot 2020-09-14 173131](https://user-images.githubusercontent.com/37020194/93098976-272a9300-f6b0-11ea-9cf9-8ff1386057e7.png)
We have this kind of code. Also we applied [UseSelection]
After some time I wrote a ef core interceptor.
![image](https://user-images.githubusercontent.com/37020194/93099183-6a850180-f6b0-11ea-97ae-7370a37796a8.png)
To go through this interceptor I override "ReaderExecuted" method.

But when I try it in REST, with kinda "return context.Programs.ToListAsync()", I go through "ReaderExecutedAsync" method in my interceptor.

So why it goes like this? With IQueryable it goes through just ReaderExecuted, not ReaderExecutedAsync?

/Regards

**Comment by TheJayMann** [comment]
My guess as to why this is, based on my knowledge of how HotChocolate works, is that HotChocolate does not know that it is dealing with EF Core, only that it is dealing with an `IQueryable`, and, because of that, does not have access to the `ToListAsync()` method, as this is not defined for any arbitrary `IQueryable` implementation.  HotChocolate still runs the process asynchronous, but does so by using `Task.Run` on the synchronous process.  One possible way that HotChocolate could make use of EF Core's asynchronous process without having to take a direct dependency on EF Core (as well as allow other `IQueryable` providers to opt in to exposing asynchronous operations to HotChocolate and others) would be to check if the `IQueryable` also implements `IAsyncEnumerable`, and use it instead of `Task.Run` when processing and returning the results.  In fact, this is what the `UseFirstOrDefaultMiddleware` and `UseSingleOrDefaultMiddleware` do.

Given that I do not recall exactly how HotChocolate middleware is called, and what code calls the first middleware, I was not able to confirm this to actually be the case, but it is something that I remember seeing.

**Comment by michaelstaib** [comment]
Version 11 now uses as @TheJayMann said IAsyncEnumerable.

**Comment by michaelstaib** [comment]
I am closing this issue since this is already addressed and the change regarding IAsyncEnumerable is already in the develop branch.

**Comment by hychencody** [comment]
So after Version 11, we are not using task.run to implement the Async? We are using EF extension methods to do the async?
