### ISSUE TITLE
Undocumented Custom Scalar Type

### ISSUE THREAD

**Issue by Beamed** [ChilliCream/hotchocolate#2322]
https://github.com/ChilliCream/hotchocolate/blob/5c28395077e2734395c3ef4cc540ac90763ffbe7/src/HotChocolate/Core/src/Types/Types/Scalars/NameType.cs#L12

Adding this type either to the documentation listing the custom scalar types Hot Chocolate provides would be very helpful. It was unfortunate to run into this issue and spend a long time investigating/debugging it because it was not listed. 

To mitigate, is there a way to prevent certain custom scalar types from being added to the schema in Hot Chocolate?

**Comment by michaelstaib** [comment]
In which context was this type added? Stitching?

**Comment by Beamed** [comment]
No, it appears this is added when creating the base Schema using SchemaBuilder.New(). When attempting to add another Name type to this schema, calling .Create() afterward leads to a duplicate Name of, uh, Name, collision.

**Comment by michaelstaib** [comment]
Can you post a code example?

**Comment by Beamed** [comment]
Sure. In the following example, kv.Key, the name of the field, is "Name":

`                schemaConfig.AddType(new ObjectType(_schemaGenerator.GenerateObjectTypeDescriptor(kv.Key,
                    kv.Value.Description,
                    false, kv.Value.Children)));
...
return schemaConfig.Create();
`
This is in the AddGraphQL portion of Services where it expects us to return an ISchema. Note that there is no C# type backing the type. 

The specific error thrown is that there is already a type 'Name' on the schema, as it is a custom Scalar provided by the Hot Chocolate library. I attempted to opt out of using it using the option to remove unused fields from schema, but it looks like schema builder will add it regardless.

**Comment by michaelstaib** [comment]
What is happening here is that somehow the types NameString is found by the type discoverer. `NameString` represents a valid GraphQL type name. This comes from the internal schema API. To me, it seems you want to fully control the type building here so you should opt-out of type inference or bind the runtime type `NameString` to a GraphQL scalar of your choosing.

Option A:

Fully explicit schema:

```
SchemaBuilder.New()
    ...
    .ModifyOptions(o => o.DefaultBindingBehavior = BindingBehavior.Explicit)
    .Create()
```

Option B:

Binding the runtime type:

```
SchemaBuilder.New()
    ...
    .BindClrType<NameString, StringType>()
    .Create()
```

BTW.... you can also do the following with the schema builder

```
SchemaBuilder.New()
    .AddObjectType(_schemaGenerator.GenerateObjectTypeDescriptor(
         kv.Key,
         kv.Value.Description,
         false, 
         kv.Value.Children));
```

Further, you can use an SDL syntax tree to build up dynamic schemas.

**Comment by Beamed** [comment]
Thanks for the background of the issue! Yup, you're 100% right that this is a scenario where I'd like the full control of the type building and not deal with type inference. Option A or B both look right up my alley, I will take a look at implementing those ASAP.

Our use case actually does use a 100% dynamic schema without backing C# types :D we've encountered a handful of issues (most impactfully #1689 ) but it's been surprisingly streamlined thanks to your library! I'll follow up shortly with how well the workaround worked :+1:

**Comment by michaelstaib** [comment]
There is also a blog post from @nigel-sampson on this:
https://compiledexperience.com/blog/posts/dynamic-graphql

One general way really is to build up a GraphQL type definition instead of using the types themselves.
We can also have a look at streamlining this further by allowing to build the types up with type definitions themselves.

@PascalSenn what do you think? Should we allow just creating a type definition and add these to the schema and we make it a type?

**Comment by michaelstaib** [comment]
@Beamed just as a background, Hot Chocolate can basically be chopped into runtime and configuration. Configuration is what happens when we build up the schema. When a type comes to live we basically in the background have a type definition. The type definition is a data structure that describes the type that we want to create. We allow it to be invalid and it only has to become valid at certain points during the configuration process.

When you, for instance, rewrite types from a schema you can intercept these definitions.

The descriptor is the end-user API to interact with the definition.

You can for instance also get access through the descriptor with these definitions by calling extend...

```
descriptor.Extend().OnBeforeCreate(definition => 
{
     // extension code
})
```

OnBeforeCreate is a lazy configuration that is executed at a certain point in time during the configuration.


Lazy configurations can also be bound to other types and create initialization dependencies.

Extend is meant to write extensions on top of hot chocolate.

But beware, we have breaking changes here with version 11 regarding type references.

**Comment by Beamed** [comment]
Hm, so my understanding was this _was_ the recommended method for creating these dynamic-driven GraphQL schemas. I saw @nigel-sampson 's post when it was made, and was surprised how similar his implementation was to mine, actually - I noticed in the response to #1689, it seemed like neither of these approaches is what you recommend for a fully dynamic schema? Can you clarify, if possible, the difference between using these type definitions and descriptors on a schema builder/configuration to generate schema, vs. the syntax type reference you mention?

**Comment by Beamed** [comment]
Following up on the recommended workarounds, both of them still continue to expose the problem. Adding an Object Type with the name of "Name" continues to cause a collision both when making the binding behavior explicit, and when explicitly binding the ClrType for NameString, presumable due to the NameType highlighted in the original post. Any other ideas? :/

**Comment by michaelstaib** [comment]
Which is correct... if you add a type two times it will have a collision. So if you add a type in this way you really create a type instance ... if you do it two times you will end up with two distinct instances that then will collide. I will write a blog post explaining the type system in-depth I think. It becomes so simple once you wrapped your head around it. Regarding dynamic schemas, we have not made this a focus point as of now. We will look into this subject after we are done with 11.

I will close this issue since this issue is solved.

**Comment by Beamed** [comment]
So to clarify, will this never be a documented scalar type? The reason I ask is because I agree with the behavior, **so long as end users know a Name scalar type is being added for them before spending engineering effort around this.** Otherwise this issue could impact end users in production unawares. There is currently no documentation telling end users this type is definitively one of the provided types, and that you are **not** allowed to opt out of Hot Chocolate creating these types. 

I understand regarding dynamic schemas. Highlighting them as not a critically supported use case would be helpful, though, to prevent other users from stumbling on some of the issues we've encountered so far. Definitely understand prioritizing here - this is a ton of incredible work, and it's important to spend time on the most impactful (and helpful towards vision) items.

As always, thank you for your time replying!

**Comment by michaelstaib** [comment]
We are. Urgently working on a brand new documentation, we will list all scalars available in there. However it will take some more time for the new docs. We expect to put more effort in at the mid of October.
