### ISSUE TITLE
Persisted GraphQL Queries

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#266]
In order to support persisted queries we want to introduce a new abstraction `IQueryStorage` that represents the query storage. 

Queries that are pulled from the query storage should already be validated so that a server does not need to do that when the query is processed.

In order to load the query into the query context we need another middleware that comes first in the pipeline and uses the storage to fetch the query.

https://github.com/apollographql/persistgraphql
https://blog.apollographql.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5
https://facebook.github.io/relay/docs/en/persisted-queries.html

**Comment by michaelstaib** [comment]
Here are some questions we still have to resolve:

- When do we validate the query?
- What about the validation configuration? Should we store a configuration hash in the db indicating when we have to revalidate a query.
- What about custom written query validations and their configurations?

**Comment by michaelstaib** [comment]
We should open another issue for creating default implementations of this storage once we agreed on a design:

- FileSystemQueryStorage
- MongoQueryStorage
- SQLServerQueryStorage
- AzureBlobQueryStorage

**Comment by michaelstaib** [comment]
https://facebook.github.io/relay/docs/en/persisted-queries.html

**Comment by michaelstaib** [comment]
#834

**Comment by michaelstaib** [comment]
we will design the abstractions for this one when we start implementing #834.

**Comment by willwolfram18** [comment]
Some thoughts I've had throughout the day thinking about this.

#### Query validation
> My suggestions assume the following in regards to how HC's query validation works:
> 1. validating the query body itself is well-formed, followed by
> 2. validating that the variables described in the body are provided and well-formed.
> If this isn't the case you can probably ignore most of my thoughts on query validation with no hard feelings 😸 

With static queries, it would be reasonable to load the queries at application start up (likely after the schema is built) and validate the query content. If validation fails at startup, the server could throw an exception and fail at start up instead of failing at the time of execution. It could then be assumed that any queries pulled from the static store(s) would be considered safe at runtime. However, you know what they say when you assume 😉 I think the most natural precaution that HC could take is to build on @michaelstaib 's suggestion: generating some kind of unique Id based on the query content (e.g. hash), and store that in memory. Then when a request attempts to use that stored query, the Id could be regenerated from the query content and compared to the startup value; if they don't match then some kind of request exception can occur (since it's possible the file is no longer present, or the database has been updated). There would still be a performance hit for generating the Id, but I would think it would be better than validating the entire query content. After the content itself, the middleware could then substitute the query content it read from the store and move on to variable validation.

With the dynamic queries that API consumers submit, those could go through the existing query validation mechanisms before being stored, meaning you should (theoretically) be guaranteed a safe query when it's read from the store. To help guarantee queries haven't been corrupted between the time the were saved and read, you could follow the same idea as above, although perhaps not keeping the Ids in memory this time since this could be an unbounded number of queries to store.

#### Using multiple storage types
The specific use case I'm thinking of is having static queries stored in one location such as a set of files, and dynamic stored queries placed somewhere else such as a database. Right now I envision the query storage registration going in 1 of 2 ways:
1. Register a single implementation of `IQueryStorage`
    - This then means an implementation of `IQueryStorage` would need to be designed specifically around accessing multiple storage locations, which could result in repeated code across projects, companies, devs, etc. if one is not provided but HC.
2. The ability to register multiple `IQueryStorage` locations and HC natively handles look ups across the access locations.
    - Similar to the first situation, this likely results in the same need for HC to provide some kind of built in support of accessing multiple storage locations

Would it be worthwhile to include some kind of `IQueryStorageCollection` to go along with this feature to allow for storage of queries across multiple locations? Or another option would be to build a `QueryStorageCollection` class that implements the `IQueryStorage` interface, and then internally it could handle the look up across multiple storage types.

The most significant issue this use cases poses though is performance; how do you efficiently search multiple storage locations without doing unnecessary look ups? If the API is designed with an asynchronous mindset and `Task`s, the performance can be slightly offset with at least a small level of parallelization. For users who need the highest levels of performance, they will likely need to roll their own solutions, but it may be possible for HC to cover at least some simple use cases.

#### Storage types
As a developer for a company who uses AWS, I notice there isn't an initial plan to support Amazon's S3 buckets. Perhaps this could be a worthwhile option to include as well? I will be 100% honest, I'm not a cloud/AWS expert, so I don't know the full scope/limitations of S3 buckets, but my understanding is that it's not uncommon to consider S3 buckets as a file storage location, so reading query content from there seems like a viable option.

**Comment by michaelstaib** [comment]
@willwolfram18 regarding the storage, I have updated the list. Since we are mostly working with Azure I did neglect AWS. It is good that you bring that up. I kicked out SQL server and mongo. Let us do local file storage, BlobStorage for Azure and S3 buckets or whatever is a good equivalent on AWS. Also we should have a look at redis for this one.

**Comment by michaelstaib** [comment]
I can do the Azure stuff.

**Comment by michaelstaib** [comment]
> With static queries, it would be reasonable to load the queries at application start up ...

This is one thing I am still not sure what the best way is. Maybe, we should have an option here. Loading at startup is in my opinion preferable, but if you deploy hc as function or lambda then this might not what we want. So, we should make that an execution option.

Important is that we mark queries as validated so that we only validate queries at startup or at runtime that weren't validated.

**Comment by michaelstaib** [comment]
Regarding the identifier let's have a string here that can be defined by the user. If not let's use a fast hash algorithm (MD5 / SHA1) since there is no security relevance here we can use MD5 or SHA1.

If the user specifies a key and sends it with its query we will take this and do no hashing. If nothing was specified we will generate the hash.

I will start work on the new UTF8 request parser and I will be able to generate a hash very efficiently when doing that in the middleware. So let us assume that we always get a key passed into the query middleware via the query request.


I am working on changing the request that is passed into the query engine:

```csharp
public interface IReadOnlyQueryRequest
{
    IQuery Query { get; } // this is the original query 

    string QueryName { get; } // this is our hash / key 

    string OperationName { get; }

    IReadOnlyDictionary<string, object> VariableValues { get; }

    object InitialValue { get; }

    IReadOnlyDictionary<string, object> Properties { get; }

    IServiceProvider Services { get; }
}
```

NOTE: We should always store and load the query as binary and not at as string. This way we are able to parse queries with out any allocation.

**Comment by michaelstaib** [comment]
> There would still be a performance hit for generating the Id, but I would think it would be better than validating the entire query content. After the content itself, the middleware could then substitute the query content it read from the store and move on to variable validation.

Yes there will be, but I also assume that it is faster then validating and parsing always. 

We at the moment have an in memory cache for queries. So, first we will check the cache and if not there we will load it from the storage.

We should have some options here:
- Allow Active Query Persistence

**Comment by willwolfram18** [comment]
As I've been thinking about this more, it feels like implementing persisted queries might benefit from a [CQRS](https://martinfowler.com/bliki/CQRS.html) design pattern. Specifically breaking the `IQueryStorage` into two interfaces like `IReadStoredQueries` and `IWriteStoredQueries` (for the dynamic query scenario). I say that because in the static query scenarios, we are really only ever concerned with reading the query from the source and then (likely) maintaining it in memory to rerun on subsequent requests. What are your thoughts on this?

**Comment by michaelstaib** [comment]
I think that sounds very good. This way you could also just implement just the read-store for a custom storage if you are only concerned with statically persisted queries. Moreover, each interface has a clear responsibility.

**Comment by michaelstaib** [comment]
This one is implemented!
