### ISSUE TITLE
Strawberry Shake Readme is Missing

### ISSUE THREAD

**Issue by nickcox** [ChilliCream/hotchocolate#2724]
The Strawberry Shake readme linked from the main readme at line 48 is empty. This makes it difficult to know how to get started.

**To Reproduce**
1. Click the 'Readme' hyperlink
2. Observe that there's nothing there

**Expected behavior**
Expected to find a readme with content

**Desktop (please complete the following information):**
 - OS: All
 - Current

**Comment by nickcox** [comment]
The [docs link on the homepage](https://chillicream.com/docs/strawberryshake) seem to be broken too.

![image](https://user-images.githubusercontent.com/135552/101111411-38d86280-362f-11eb-96e0-4d66cbcc08b0.png)

**Comment by michaelstaib** [comment]
Thanks for reporting this.

**Comment by chlumper** [comment]
Till the issue is resolved the following links to the blog entries regarding Strawberry Shake might be helpful:
* [Building a real-time .NET GraphQL Client API](https://chillicream.com/blog/2019/11/25/strawberry-shake_2) [[.md]](https://github.com/ChilliCream/hotchocolate/blob/main/website/src/blog/2019-11-25-strawberry-shake_2.md)
* [Building a .NET GraphQL Client API](https://chillicream.com/blog/2019/09/27/strawberry-shake) [[.md]](https://github.com/ChilliCream/hotchocolate/blob/main/website/src/blog/2019-09-27-strawberry-shake.md)
