### ISSUE TITLE
Single query exhausting database connection limit (v11 migration)

### ISSUE THREAD

**Issue by tsykes2020** [ChilliCream/hotchocolate#2806]
After migrating to v11, the db connection pool seems to have some issues with the way HotChocolate interacts with it.
We are using a postgres db with the default limit of 100 connections, and EF Core with a `DbContext` pool with a limit of 64.

The client issues a 2-level query (something equivalent to `query { groups { name project { name } }`), and when there are a sufficient number of groups (a realistic figure, ~130, not a large number) then over the course of resolving the query the database hits its connection limit, causing not only this query to fail but also blocking anything else the app is doing.

Using an `IDbConnectionInterceptor` to track open connections, it looks like the issue is that connections aren't closed immediately on release from the pool, but there is some delay. This means that the rapid-fire way that HotChocolate rents and returns from the pool can create a situation where the pool stays within its 64 `DbContext` limit, but the number of open connections exceeds the database limit.

In this case the issue happens to be occurring when resolving a single query with ~130 elements, but some testing shows that the same problem can occur with several concurrent smaller queries. The common cause behind these seems to be the rate of renting and releasing from the `DbContext` pool.

**Comment by tsykes-2020** [comment]
This _may_ not actually have anything to do with the `DbContext` pooling, but is instead due to concurrent connections on those `DbContext`s. This seems to be due to HotChocolate not limiting how many concurrent queries it issues which can quickly exhaust any connection limit, especially with multiple concurrent client requests.

**Comment by tsykes-2020** [comment]
After extensive digging, tuning Npgsql's connection pooling I think has resolved this issue for us (more testing needed to be sure). It is worth being aware that `IDbContextPool` can transiently open many more connections than the pool limit though

**Comment by ademchenko** [comment]
@tsykes-2020, we also have pretty loaded solution with postgresql database. How did you solve it?

**Comment by tsykes-2020** [comment]
@ademchenko First thing, if you are using Npgsql, add `;Pooling=true;Maximum Pool Size=50` to your connection string (tune the pool size as appropriate, remember that this pool is per replica so you may want to go much lower). According to the docs, the default is pooling enabled with a pool size of 100, but I'm not sure that that is the case, so set them explicitly in the connection string to be sure.

Secondly, consider using pgbouncer as a second layer of connection pooling, either per-client or one per postgres server. Npgsql causes some log spam in pgbouncer, but neither team seems to be investigating the issue
https://github.com/pgbouncer/pgbouncer/issues/277
https://github.com/npgsql/npgsql/issues/2522
but there is a PR to lower the priority of the messages, which has been open for some time
https://github.com/pgbouncer/pgbouncer/pull/424

We found that with pgbouncer is was essential to increase the `listen_backlog` much higher than the default (around 5000 seems to be ok) which does suggest to me that maybe something else isn't quite right. If the `listen_backlog` is too low, then when there is a burst of queries, some of them will be dropped by pgbouncer, which will lead to them timing out in the app after 30s. I'm not sure why this happens, because Npgsql should already be pooling connections to pgbouncer making the listen backlog unnecessary, so clearly something else is going on, but it sort of works for now but I don't have full confidence in the setup at this point.

Hope this helps at least get you on track

**Comment by PascalSenn** [comment]
This is solved in v12 with DB Context Pooling
