### ISSUE TITLE
[UseFirstOrDefault] generates sql that take all rows instead of first

### ISSUE THREAD

**Issue by abdullahgb** [ChilliCream/hotchocolate#2878]
**Describe the bug**
It seems by using [UseFirstOrDefault] directive returns first row, but generated sql on MS SQLServer, takes all rows. I think, firstOrDefault is executing on ClientSide

**To Reproduce**
### QueryType
```

> public class BusinessTypeQueryType : BaseQueryType
    {
        [UseDbContext(typeof(BaseQueryContext))]
        [UseFirstOrDefault]
        [UseProjection]
        [UseFiltering]
        public IQueryable<BusinessType> BusinessTypes([ScopedService] BaseQueryContext _context)
        {
            return _context.BusinessTypes;
        }
    }
```
### Generated SQL
> SELECT [b].[BusinessTypeID], [b].[Category], [b].[Code], [b].[BusinessTypeName]
FROM [app].[BusinessType] AS [b]

**Expected behavior**

> SELECT TOP (1) [t0].[BusinessTypeID], [t0].[BusinessTypeName], [t0].[Code], [t0].[Category]
> FROM [app].[BusinessType] AS [t0]

**Desktop (please complete the following information):**
 - OS: Windows 10 (19041
 - Version 11.0.7

**Comment by gojanpaolo** [comment]
`SingleOrDefault` also has the same issue. And `SQLite` can also be used to reproduce

**Comment by gojanpaolo** [comment]
It might be because the result is converted to `IAsyncEnumerable/IEnumerable`

https://github.com/ChilliCream/hotchocolate/blob/f73cdfa2d55ca652cedac9d5b6a87e72ea6c9a14/src/HotChocolate/Data/src/Data/Projections/FirstOrDefaultMiddleware~1.cs#L30

https://github.com/ChilliCream/hotchocolate/blob/f73cdfa2d55ca652cedac9d5b6a87e72ea6c9a14/src/HotChocolate/Data/src/Data/Projections/FirstOrDefaultMiddleware~1.cs#L46
