### ISSUE TITLE
Finalize Tabs

### ISSUE THREAD

**Issue by fredericbirke** [ChilliCream/hotchocolate#2930]
Please see https://github.com/ChilliCream/hotchocolate/pull/2810#issuecomment-766343514

**Comment by tobias-tengler** [comment]
The tabs looking bad with text before code (as seen in the linked comment) is no longer an issue:
![image](https://user-images.githubusercontent.com/45513122/119652725-c3538f00-be26-11eb-9981-3afaa8c1e300.png)

The tabs still look the same, but I think they look alright.
Since those are the only two things mentioned in the comment, I'm going to close this issue. If you already have a concrete vision for the design of the tabs, fell free to re-open and edit the issue to be about the tab design.
