### ISSUE TITLE
Rename ServiceAttribute to FromServicesAttribute

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ChilliCream/hotchocolate#2990]
**Is your feature request related to a problem? Please describe.**

I want to easy move code back and forth from Controllers to GraphQL and back.

**Describe the solution you'd like**

Either hotchocolate to undrestand ASP.NET FromServicesAttribute or rename its ServiceAttribute to FromServicesAttribute. It is similar to way AuthorizeAttribute is done, same name - different namespace.

**Describe alternatives you've considered**

`[Service]` is shorter, but `[FromServices]` already known and used.

**Comment by michaelstaib** [comment]
- Renaming the attribute would be a breaking change that I think does not add value.
- Adding an additional attribute is also not what would be good since it would burden us to describe both ways and even line out why we have both. Apart from that, we would introduce collisions between these types.
- Binding the ASP.NET core attribute is something we could do. But it would add dependencies to the type system core. I would rather like to not depend on ASP.NET core in the type system core. Also, if we support one attribute, we would need to add the others for consistency, and most of them do not make sense in the GraphQL context.

@PascalSenn opinions?

**Comment by PascalSenn** [comment]
I agree that this dependency would not be nice.  
I think that the current state of the `[Authroize]` attribute is also not idea.
It happens often that the wrong attribute is used. So having two attributes with the same name is something we have to avoid

@michaelstaib this sits in the resolver compiler right? We could make `IResolverParameterCompiler` public and add a configuration interface for it. This way we could have a compatibility package.

**Comment by michaelstaib** [comment]
The resolver compiler is on the list. Lets wait on that and see how we integrate with source generator.

**Comment by michaelstaib** [comment]
Closing this issue.

**Comment by dzmitry-lahoda** [comment]
fixed with https://github.com/ChilliCream/hotchocolate/issues/3083 , thanks
