### ISSUE TITLE
High- CVE-2020-1045- Indirect dependency -microsoft.aspnetcore.http.2.1.1

### ISSUE THREAD

**Issue by chougulenishant8** [ChilliCream/hotchocolate#3302]
**High- CVE-2020-1045- Indirect dependency -microsoft.aspnetcore.http.2.1.1**
From DevSecOps scan, we observed HotChocolate.AspNetCore has an indirect dependency of microsoft.aspnetcore.http.2.1.1 which is vulnerable to (CVE-2020-1045) bypass vulnerability of ASP.NET core cookie.
https://www.whitesourcesoftware.com/vulnerability-database/CVE-2020-1045
![image](https://user-images.githubusercontent.com/44156890/111483866-96d71480-870b-11eb-887e-dd6fc7fc49be.png)

**To Reproduce**
Code package location below

![image](https://user-images.githubusercontent.com/44156890/111483361-1c0df980-870b-11eb-8cfd-a9c391213b4e.png)

**Remediation**
Upgrade to version microsoft.aspnetcore.app - 2.1.22,microsoft.aspnetcore.all - 2.1.22,microsoft.netcore.app - 2.1.22, Microsoft.AspNetCore.Http - 2.1.22

**Comment by michaelstaib** [comment]
You screenshot is from Hot Chocolate 10.5. 

Hot Chocolate 11 does not have this reference.

**Comment by michaelstaib** [comment]
Ah, I see you are mixing version dependencies.
Mixing version 10.5 and 11 assemblies can lead to a lot of runtime issues like method not found exceptions.

Furthermore, we have deprecated the Playground package. If you want to use playground integrate the playground react app in your server and do not use our package since we are not updating the js packages anymore. I guess there are also lots of deprecated packages in the version of playground.

**Comment by mmisztal1980** [comment]
Hi @michaelstaib , sorry to necro this issue, but it seems that the `HotChocolate.AspNetCore.Voyager` which is still at version `10.5.5` has the forementioned dependency. 

What's the recommendation here? Is there an alternative to the Voyager?
