### ISSUE TITLE
Cannot add authentication/authorization to introspection calls by extending and adding @authorize directive to introspection types

### ISSUE THREAD

**Issue by PeterL328** [ChilliCream/hotchocolate#3417]
**Describe the bug**
We're trying to require authentication for introspection calls. We've configured our JWT validation and added the `.AddAuthorization()` from the `HotChocolate.AspNetCore.Authorization` package. We've tried adding the @authorize directive to the `Query` type **and it works** to require authentication for all queries including introspection calls but we would like to only require authentication on certain calls so we prefer not to write it like so:
```
type Query @authorize {
  hello: String
}
```
The other option we tried and **didn't work** but would like it to work was extending the introspection types and adding the @authorize directive to require authentication for introspection calls. The below doesn't work and still allows introspection calls for unauthenticated users.
```
extend type __schema @authorize{
}
extend type __type @authorize{
}
extend type __typename @authorize{
}

type Query  {
  hello: String
}
```

**To Reproduce**
1. Copy the above schema and create a `schema.graphql` file.
2. Configure your JWT validation
2. Configure the GraphQL service
```csharp
// Configure GraphQL service
services.AddGraphQLServer()
        .AddDocumentFromFile(SchemaFilePath)
        // Add authorization for GraphQL calls
        .AddAuthorization()
        // Bind GraphQL Types
        .BindComplexType<Query>()
```
3. Start the GraphQL service
4. Make some introspection calls and you're call should still succeed even if you are unauthenticated (i.e. don't pass any bearer token)
```
{
  __schema {
    queryType {
      name
    }
  }
}
```

**Expected behavior**
If the user is unauthenticated and makes an introspection call by extending and adding @authorize directive to the introspection types, then they should get `AUTH_NOT_AUTHENTICATED` as result.

**Desktop (please complete the following information):**
- HotChocolate.AspNetCore (11.1.0)
- HotChocolate.AspNetCore.Authorization (11.1.0)

**Comment by michaelstaib** [comment]
```graphql
extend type __schema @authorize{
}
extend type __type @authorize{
}
extend type __typename @authorize{
}
```

These types do not exist in GraphQL. What you want to extend are the introspection fields on the `Query` type.

```graphql
extend type Query {
    __typename: String! @authorize
}
```

However, since introspection I think it would be better to handle this in a completely different part of the execution.

First, you should not limit `__typename` since it is very cheap, is only returning the typename and is used by many tools. `__schema` and `__type` are the things that make sense to be secured.

Second, if someone has no rights to execute introspection we should just reject the whole request. This is different with business fields. 

Rejecting the whole query can be done very efficiently with a document validation rule. So essentially we can just inspect the query for introspection and if we find any introspection usage we will check if that person is authenticated.

**Comment by michaelstaib** [comment]
We are making this easier with the next preview build since this is a frequent request by the community.

In order to control when introspection is allowed you can enable the introspection validation rule which will evaluate if the current request allows for introspection.

```csharp
services
    .AddGraphQLServer()
    .AddIntrospectionAllowedRule();
``` 

The rule itself does the hard work of analyzing the GraphQL query for violations.

In order to control if a request is allowed to use introspection you need to provide context data through the HTTP request interceptor:

```csharp
public class CustomHttpRequestInterceptor : DefaultHttpRequestInterceptor
{
    public override ValueTask OnCreateAsync(
        HttpContext context,
        IRequestExecutor requestExecutor,
        IQueryRequestBuilder requestBuilder,
        CancellationToken cancellationToken)
    {
        requestBuilder.AllowIntrospection();
        
        await base. OnCreateAsync(context, requestExecutor, requestBuilder, cancellationToken);
    }
}
```

The request interceptor is registered like the following:

```csharp
services.AddHttpRequestInterceptor<CustomHttpRequestInterceptor>();
```

**Comment by PeterL328** [comment]
Hey Michael,
Thanks for the quick reply!
We tried adding 
```
type Query {
  hello: String @authorize
}

extend type Query {
    __typename: String! @authorize
}
```
but got an error 
```
System.ArgumentException: An item with the same key has already been added. Key: __typename
```

We'll continue with adding the @authorize directive with the Query type like the below and wait until the newer feature comes out for better introspection control.
```
type Query @authorize {
  hello: String
}
```

Thanks!

**Comment by michaelstaib** [comment]
This feature is now implemented with:
https://github.com/ChilliCream/hotchocolate/releases/tag/11.2.0-preview.5
