### ISSUE TITLE
StrawberryShake: Source generation fails occasionally on rebuild

### ISSUE THREAD

**Issue by braidenstiller** [ChilliCream/hotchocolate#3435]
StrawberryShake on v11.1

When doing a rebuild in a Blazor WASM project, occasionally the following error happens:

`warning CS8785: Generator 'CSharpClientGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'GraphQLException' with message 'Could not find file '...\bin\Debug\net5.0\GraphQL\.graphqlrc.json'.'`

Usually a subsequent build or rebuild can fix the issue.

I have a feeling this may be caused by the pre-build clean which clears away the .json file.

**Comment by michaelstaib** [comment]
Interesting

**Comment by michaelstaib** [comment]
This might be fixed with preview.10 .... could you retest?

**Comment by braidenstiller** [comment]
Resolved in 11.2.0-preview.12
https://github.com/ChilliCream/hotchocolate/releases/tag/11.2.0-preview.12

**Comment by braidenstiller** [comment]
Still occurring on initial rebuild after resyncing schema.

**Comment by braidenstiller** [comment]
Can confirm still happens as of v11.2.0 on rebuild after graphql update.

`warning CS8785: Generator 'CSharpClientGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'GraphQLException' with message 'Could not find file '...\bin\Debug\net5.0\GraphQL\.graphqlrc.json'.'`

I'm concerned this may fail in Azure pipelines because the bin folder would be empty. I will be able to test and confirm by end of week.

**Comment by thunder7553** [comment]
I do encounter such error again and again as well. I had the .graphqlrc.json initially in an subfolder, and got the information that strawberry shake needs the name of the client in the .graphqlrc.json file. As it turns out, a .graphqlrc.json was created in the project root, containing the document and schema links to the sub directory, but with no client configuration. Ok, some bug, I thought. And changed the structure by creating a new client (using the StrawberryShake Visual Studio Addin), not using subfolders. Worked again for some time, then it suddenly stopped working, and my .graphqlrc.json was replaced by version not containing the strawberryshake configuration. 

I downloaded the hotchocolate source code (https://github.com/ChilliCream/hotchocolate) just now and tried to find where this was written - but I could not find a write for it (I ony saw some places where it was read). 

I suppose this has something to do with some visual studio extension replacing the .graphqlrc.json, but I could not find out which one. I did not find the source code for the strawberry shake visual studio extension, and I don't have any other GraphQL related extension installed (to my knowledge). My next step is to disable the StrawberryShake extension and see if the problem persists.
