### ISSUE TITLE
How to add middleware without directive?

### ISSUE THREAD

**Issue by featherbits** [ChilliCream/hotchocolate#364]
I would like to hook custom delegate before field is resolved without decorating schema field with directive? Is that possible? Something like described in here https://hotchocolate.io/docs/next/directive-middleware#middleware but without actual directive. Something that I can add to schema configuration and it would execute before any field is resolved with possibility to override result of that field.

**Comment by michaelstaib** [comment]
Hi,

this would be actually this PR #363

Will come with the next version.... 


we are introducing then three kinds of middlewares:
- Query Middleware
  This will basically allow you to rewrite and modify requests  (this is needed for our schema stitching framework)

- Field Middleware
  This will integrate to all field resolvers.

- Directive Middleware
  This is a selective middleware that only includes itself if annotated

**Comment by michaelstaib** [comment]
we will provide a preview of this feature tomorrow night with 0.7.0-preview.2

**Comment by michaelstaib** [comment]
[0.7.0-preview.2](https://github.com/ChilliCream/hotchocolate/releases/tag/0.7.0-preview.2) is building now

Here is how to use it:

```csharp
Schema.Create(c => {
   c.Use(next => context => 
   {
        next(context);
        if(context.Result is string s) 
        {
             context.Result = s.ToUpper();
        } 
   });
}); 
```

Field Middlewares are built into every field resolver during schema creation, so they will always run. This is opposed to directive middlewares.

So, an instrumentation middleware would be best implemented as directive middleware since it could be annotated to the whole request or just to problem fields to get performance insights. 

Some other middlewares are better written as field middleware since those are always executed. resolver

**Comment by michaelstaib** [comment]
Please remember that we are still working on this feature. Query middlewares are not yet included and last but not least feedback is welcome :)

**Comment by michaelstaib** [comment]
I will close this issue... Feedback can be added to #338
