### ISSUE TITLE
github link broken

### ISSUE THREAD

**Issue by AlegntayeYilma** [ChilliCream/hotchocolate#3738]
**Describe the bug**
"There are example projects for both in our [repository](https://github.com/ChilliCream/hotchocolate/tree/master/examples) on GitHub."  the url 'https://github.com/ChilliCream/hotchocolate/tree/master/examples' is not working. 

**To Reproduce**
1. Go to documentation for asp.net
2. Click on  repository

**Expected behavior**
A Github section for asp.net examples

**Comment by damikun** [comment]
@AlegntayeYilma  Is that in V10 docs ?

(https://chillicream.com/docs/hotchocolate/v10/server) ?? 

 V10 Docs are not maintained much since there is new version V11 and V12 is coming out... There is no fixes for V10 the build system is not more working for V10... You can use directly new Docs...
 
 All examples are present in new repo:
 https://github.com/ChilliCream/hotchocolate-examples
 
 For community libs:
 https://github.com/ChilliCream/hotchocolate/blob/develop/COMMUNITY.md

**Comment by tobias-tengler** [comment]
The ASP.NET example can be found [here](https://github.com/ChilliCream/hotchocolate/tree/main-version-10/examples/AspNetClassic.StarWars).

If you are starting a greenfield project, we highly recommend choosing version 11 with ASP.NET Core though!
