### ISSUE TITLE
Rename ScopedService

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#3944]
**Is your feature request related to a problem? Please describe.**
Reading `ScopedService`, as an ASP.NET Core developer new to Hot Chocolate, my immediate assumption would be that it is about service lifetime. (I myself had this misconception for the longest time)

This misconception is furthered by the Entity Framework example on the website where we are using `[ScopedService]` to inject the database context... which has a scoped service lifetime... which must mean that we are using `ScopedService` because of the DbContext lifetime - 🚨 WRONG.

**Describe the solution you'd like**
`ScopedService` should be renamed to more accurately reflect its purpose. Maybe to something like `FromLocalState`? Or we could have it so that the existing `LocalState` attribute takes the name of the parameter type as its key, if the key is not specified.

**Comment by PascalSenn** [comment]
I'm with you @tobias-tengler 
@michaelstaib  can we deprecate ScopedService with 12?

**Comment by michaelstaib** [comment]
We can if we find a better name :) So far did not find one. The name is not totally wrong since it actually is a scoped service lifetime. The lifetime if scoped services in this case is scoped to the filed. The misconception is often that scoped means per request. But scoping is up to the user.

But I agree that there is an issue here since we scope out of the service context. We could actually remedy this but also would break behavior in this case.

I see the issue that people do not get what it does. Although it does what it says :D it scopes the lifetime of a service to the pipeline of a resolver.

**Comment by PascalSenn** [comment]
@michaelstaib  I vote for LocalService

**Comment by syedqutub** [comment]
is there a way to register ScopedService in the service container with out describing it in the pipeline?

**Comment by tobias-tengler** [comment]
Closing this, since the new `RegisterDbContext<T>()` makes the `ScopedServiceAttribute` obsolete for the majority of today's use-cases.
