### ISSUE TITLE
Everything relating to the ID scalar should be moved outside of the Relay namespace

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#3991]
**Is your feature request related to a problem? Please describe.**
Currently everything, but the `IdType`, like the `IDAttribute` or the `ID()` descriptor extensions live in the `Relay` namespace.

This doesn't make sense to me, as the ID scalar and its requirement for uniqueness are part of the [GraphQL specification](https://spec.graphql.org/June2018/#sec-ID) and not something Relay specific.

**Describe the solution you'd like**
I would like to extract the following things out of the `Relay` namespace:
- RelayIdFieldExtensions (should be just IdFieldExtensions going forward)
- GlobalIdInputValueFormatter
- IdMiddleware
- IdSerializationException
- IdSerializer
- IdValue
- IIdSerializer

As the wish to extract the Relay specific functionality into a separate package came up recently, I think this would be a good change to perform, when the new package is introduced.

**Comment by michaelstaib** [comment]
The `ID` behavior is not specified in the spec. It is rather more about semantics in there.

> GraphQL is agnostic to ID format, and serializes to string to ensure consistency across many formats ID **could** represent, from small auto‐increment numbers, to large 128‐bit random numbers, to base64 encoded values, or string values of a format like GUID.

Regarding to the spec the ID format could be quite a range of things. Only the relay spec defines that it has to be encoded and that there is a node field and stuff like that. The `IDAttribute` and `ID` extension add the relay ID specific serializer to any field and by thus do not allow the field to be all that the spec would allow.

The `IDAttribute` represents the implementation of the `ID` behavior represented by the relay spec.

However, maybe we should rename these to be `GlobalIdAttribute` and `GlobalId` to make that more clear.

@benmccallum what are your thoughts on that?

**Comment by michaelstaib** [comment]
Regarding uniqueness, the relay spec lays out a very specific way to format the ID and a very specific way to make keys unique. This is essentially the main benefit these helpers introduce.

**Comment by tobias-tengler** [comment]
Yes, I think `[GlobalId]` makes the connection to `AddGlobalObjectIdentification` more clear.
But something like `[ID]` should also stay in my opinion, as a shorthand for `[GraphQLType(typeof(IdType))]`. It having the same name is likely going to cause issues with people migrating though, so I'm not sure how we could go about it. Maybe `[IdField]`?

**Comment by benmccallum** [comment]
I think given that the ID scalar is defined in the GraphQL spec, it should stay in the namespace it currently is.

I agree with Michael that the Relay-specific way of implementing that `ID` stays in a Relay-specific namespace/package. Conceptually it's like `ID: String!` is the contract, and `AddGlobalObjectIdentification` is registering the Relay implementation.

I would be in favour of a rename of `IDAttribute` to `GlobalIdAttribute` since Global Id seems to be the terminology in Relay and it'd make more sense with the `AddGlobalObjectIdentification` definitely.

In terms of keeping `ID`, I'd say it's dropped for v12 entirely, and in the breaking changes notes we make a note that if you were using it just for typing to a scalar, here's a simple `IDAttribute` to do that, and whack in a sample as it's pretty easy. But it's really just a find and replace. Keeping it in a way that just types to `ID` would be a mistake IMO, at least for a few more major versions, as people would assume their code is working if it compiles but not realize the attribute no longer applies all the relay middleware that some folks would need.

Sorry Tobias :P Interesting discussion though. 

I now regret calling our library `AutoGuru.HotChocolate.PolymorphicIds` when the spec uses the word "coercion" which is much clearer. D'oh!

**Comment by tobias-tengler** [comment]
@benmccallum Thanks for the input :)

I'll go ahead and create a new issue for the `GlobalId` part and close this one.

Just to make sure I understood your point about the `ID` correctly: You'd like to remove it entirely and make a note to either use the `GlobalId` or a tutorial on how to create an attribute as shorthand for the `IdType`?

**Comment by benmccallum** [comment]
I just meant if rename it to GlobalIdAttribute, we should not keep an IDAttribute that behaves differently (e.g. just sets the type) at least for a few major versions.

I'm not sure if people are using the attribute just for the type setting, but we could just show them how to do that in a code example in the breaking changes docs. Basically
```Public class IDAttribute { 
... descriptor.Type<IdType>();
}```

If they wanted that convenience. I think it's too risky doing that ourselves for a while. We could do an IdAttribute I guess :P 

On my phone :p

**Comment by benmccallum** [comment]
Basically let's rename it for sure.

And optionally show people how to make an attribute that sets the type only if someone finds that useful.
