### ISSUE TITLE
Custom Scalar Support

### ISSUE THREAD

**Issue by scottrabara** [ChilliCream/hotchocolate#433]
Hi, I've been using the HotChocolate library for some time now and am getting around to trying out custom scalar types. When a scalar type is given a unique name such as "CustomLong", it can be registered just fine and used within my other types as input/output.

```cs
public class CustomLongType : ScalarType
    {
        public CustomLongType() : base("CustomLong")
        {
        
        }
        ...
    }
```

Via your documentation, it mentions the ability to swap out the built-in base Scalar types. I have tried to swap out your guys' long scalar type to be able to add my own custom behavior, but have not been able to do so. Defining my `CustomLongType` like such:

```cs
public class CustomLongType : ScalarType
    {
        public CustomLongType() : base("Long")
        {
        
        }
        ...
    }
```

This seems to fail to register the type correctly in TypeRegistry as the _namedTypes dictionary will pull back the built-in ScalarType for long `{HotChocolate.Types.LongType}`

```cs
private void TryUpdateNamedType(INamedType namedType)
{
	INamedType namedTypeRef = namedType;

	if (!_namedTypes.TryGetValue(namedType.Name, out namedTypeRef))
	{
		namedTypeRef = namedType;
		_namedTypes[namedTypeRef.Name] = namedTypeRef;
	}
        ...
}
```

Should there be something here to check for IsScalarType to swap with?

Is there a better way to do such swapping? Is this type of swap allowed? Let me know if I am doing something completely wrong!

**Comment by michaelstaib** [comment]
Hi Scott,

I will have a look at that sometime tonight.

**Comment by michaelstaib** [comment]
Hey Scott, 

I will move this one to Version 0.8.0. In version 0.8.0 we have a lot of schema enhancements and I think this is a better fit for that release. 0.7.0 is more about middleware, execution engine and co.

**Comment by michaelstaib** [comment]
The scalar types are registered by the `SchemaContextFactory`. The schema context is the internal initialization context for the schema.

The factory has two functions that preregister scalar types (`RegisterSpecScalarTypes` and `RegisterSpecScalarTypes`).

All types that are preregistered by the SchemaContextFactory cannot be changed. This behavior is correct since we do not want people to meddle with the spec scalars or the introspection types.

What is wrong is to register the extended scalars here.

So my suggestion is to remove the `RegisterExtendedScalarTypes` from that class and create a new extensions method in `SchemaConfigurationExtensions` called `RegisterExtendedScalarTypes` that registers those types.

With that users of the API could register the package with one line of code and use HC like before or the could register just some of those types by manually registering them.

**Tests**

- [ ] Test that shows that the extended types are not registered without calling  `RegisterExtendedScalarTypes` on `ISchemaConfiguration`
- [ ] Test that proves that custom scalars for can be registered.
- [ ] Test that proves that the spec scalars cannot be swapped out.
- [ ] Test that shows that all extended types are correctly registered when `RegisterExtendedScalarTypes` on `ISchemaConfiguration` is called.

**Changelog**

- [ ] Update the change log ([Unreleased] section)

**Documentation**

- [ ] We need to update the section https://hotchocolate.io/docs/next/custom-scalar-types
  Maybe we should rename that section to scalar types and then state what are the spec types (table) show what extended types we provide and how they can be registered.

**Comment by scottrabara** [comment]
@michaelstaib Documentation and changelog have been updated, please see PR's referencing this issue above.

**Comment by michaelstaib** [comment]
@scottrabara I will close this one since everything is implemented.
