### ISSUE TITLE
Lack of IQueryValidationRule

### ISSUE THREAD

**Issue by marmited** [ChilliCream/hotchocolate#4399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to implement the solution for n+1 problem which is described on this blog: [https://compiledexperience.com/blog/posts/graphql-n+1](https://compiledexperience.com/blog/posts/graphql-n+1)

I have a problem, because i am not able to find IQueryValidationRule interface in 12 version of your framework.
Is there any different way to achieve this goal?

### Steps to reproduce

1. 

### Product

Hot Chocolate

### Version

12.1.0

**Comment by michaelstaib** [comment]
The visitors and the validation rules have been completely overhauled. 

With the new API you do not necessarily implement a rule you can also just implement a validation visitor and HC will generate the rule for the visitor.

A visitor in this case must inherit from `HotChocolate.Validation.DocumentValidatorVisitor` which is based on our new visitor class that is more flexible but also comes in some cases with more complexity.

The main change here is that you have enter and leave methods.

In order to register your validation visitor do the following:

```csharp
services
    .AddGraphQLServer()
    ....
    .AddValidationVisitor<MyCustomValidationVisitor>();
```

There is also one additional setting you can consider. In general validation rules are catchable, meaning we will hash the document and only run the validation once on the document for the entire lifetime of the server.

However in some cases you might want to take request properties into account like the header or even the currently signed in user into account. In these case you can mark such a validation rule as not cachable, meaning it needs to be executed every single time we execute a request.

```csharp
services
    .AddGraphQLServer()
    ....
    .AddValidationVisitor<MyCustomValidationVisitor>(isCacheable: fase);
```
