### ISSUE TITLE
Create Metapackages for AspNetCore and AspNetClassic

### ISSUE THREAD

**Issue by rstaib** [ChilliCream/hotchocolate#445]
- [ ] HotChocolate.AspNetCore.All
- [ ] HotChocolate.AspNetClassic.All

**Comment by michaelstaib** [comment]
We will leave the package structure for now hand re-decide on version 10. I will close this issue.

**Comment by OneCyrus** [comment]
any chance we could reconsider this, @michaelstaib? i see two benefits for this:

**Developer Experience**
There are a lot of issues because people aren't adding all the needed packages for certain features. Adding just one package and everything works would be quite nice.

**CI/CD**
we are using CI/CD for auto updating dependencies. Updating full HotChocolate with one dependency would reduce a lot of manual actions.
