### ISSUE TITLE
Configure Identity for graphql using HotChocolate?

### ISSUE THREAD

**Issue by WaadSulaiman** [ChilliCream/hotchocolate#4450]
### Is your feature request related to a problem?

There seems to be a problem when trying to configure Identity with hot chocolate. Could someone please help?

### The solution you'd like

Explanation about configuring Identity with hotchocolate. 

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
These questions are better in the slack channel ... in general identity server works just fine since it's only asp.net core that you connect here. We as a project cannot help you on this, we can just give the space on slack to discuss such things. I am closing this issue since we use the issues for tracking new features and bugs.

**Comment by WaadSulaiman** [comment]
Please why won't someone just answer? I did ask on slack, asked on stackoverflow, wrote a question in Microsoft Q/A. I haven't seen 1 single response 😕. Not only that, I have googled like 50 times, went on YouTube, read the documentations. I just want to configure Identity. Sincerely 😩
