### ISSUE TITLE
Geometry is not mapped automatically

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#4516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Geometry is not mapped automatically

https://github.com/bishrant/GeometryGraphQL

### Steps to reproduce

1. Run the solution of @bishrant

### Product

Hot Chocolate

### Version

12.4.0

**Comment by PascalSenn** [comment]
@bisrant 
i was looking in this issue
We bind the GeometryType scalar explicitly as it is not clear if you either want the Scalar or the Interface type. 

If you want to use the Scalar type you can do this:
```csharp
.AddType(new GeometryType("Geometry", BindingBehaviour.Implicit);
```

if you want to use the interface type you have to bind it directly on the geometry field.
Either through
`[GraphQLType(typeof(GeoJsonInterfaceType))]`

or code first
```csharp
descriptor.Field(x => x.TheGeometryField).Type< GeoJsonInterfaceType>();
```

I am going to close this issue, feel free to open one if things are not clear :)

**Comment by bishrant** [comment]
@PascalSenn Thanks for the clarification. I was scouring the docs and somehow missed that `AddType` thing was only doing `AddSpatialTypes()`. I think I got it working now when I replaced `.AddSpatialTypes()` with `.AddType(new GeometryType("Geometry", BindingBehavior.Implicit))`.

I will report back if I notice something else not working.

**Comment by clintsinger** [comment]
I found this issue after commenting on https://github.com/ChilliCream/graphql-platform/issues/6645.  If I follow these instructions the `Geometry` error does go away but you aren't able to include the `.AddSpatial()` for the remaining types.   

You can manually add all of the other types except for the 
```
.TryAddConvention<ISpatialConvention>(conventionFactory())
.TryAddTypeInterceptor<GeometryTransformerInterceptor>()
```

due to them being internal.

Is there a possible fix that satisfies being able to use `.AddSpatial()` and to also get what everyone seems to need which is a call to `.AddType(new GeometryType("Geometry", BindingBehavior.Implicit))`?
