### ISSUE TITLE
 How to make ExceptionHandlerMiddleware work

### ISSUE THREAD

**Issue by kou-h** [ChilliCream/hotchocolate#4527]
### Is your feature request related to a problem?

We are migrating graphql.net to hotocollate.
The original ExceptionHandlerMiddleware does not work in hotocollate.

### The solution you'd like

What should I do？

### Product

Hot Chocolate

**Comment by tobias-tengler** [comment]
Hot Chocolate and graphql-dotnet are two completely different projects.
Could you please explain what the mentioned middleware does and what behavior you would expect in Hot Chocolate.

Asking this question in [our Slack](http://slack.chillicream.com/) would probabaly also make sense, dince this is more of a community question.

**Comment by kou-h** [comment]
Thank you for your reply. ExceptionHandlerMiddleware handles all exceptions and returns error information and HttpCode: 500

**Comment by tobias-tengler** [comment]
Hot Chocolate automatically transforms exceptions into GraphQL spec compliant errors. A HTTP 500 status code is only produced, if the exception prevents the `data` field from being populated. 

If you 100% need custom status codes, you can use the [IHttpResultSerializer](https://chillicream.com/docs/hotchocolate/api-reference/aspnetcore/#serialization), but I would not recommend it, as this might make your GraphQL server not spec compliant and introduce issues for clients.

**Comment by michaelstaib** [comment]
https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md

**Comment by michaelstaib** [comment]
There were edits 12 days ago... we will include the latest edits with the next release.

**Comment by michaelstaib** [comment]
I have looked at the error handling of GraphQL-DotNet and it seems they do something like:

```
options.UnhandledExecutionDelegate = ctx =>
{
    if (ctx.Exception is SqlException)
        ctx.ErrorMessage = "A database error has occurred.";
};
```

Is that what you are looking for?

In HotChocolate, this works; differently, we have something called a `IErrorFilter`.

```csharp
/// <summary>
/// An error filter can handle and rewrite errors that occurred
/// during execution.
/// </summary>
public interface IErrorFilter
{
    /// <summary>
    /// OnError is called whenever an error occurred during
    /// execution of a query.
    /// </summary>
    /// <param name="error">
    /// The error that occurred. This argument cannot be null.
    /// </param>
    /// <returns>
    /// Returns the error passed in to this filter or a rewritten error.
    /// It is not allowed to return null.
    /// </returns>
    IError OnError(IError error);
}
```

Hot Chocolate will automatically create a GraphQL error object from any unhandled `Exception`. That error is passed to the registered `IErrorFilter` pipeline, and the error filter can choose to just pass it along or transform it.

The error object has the original exception preserved on the object. The exception will be stripped at the end of the pipeline so that it does not go to the serialization.

This is how you register an error filter:

```csharp
services
    .AddGraphQLServer()
    .AddQueryType<Query>()
    .AddErrorFilter(error =>
    {
        if (error.Exception is NullReferenceException)
        {
            return error.WithCode("NullRef");
        }
        return error;
    });
```

You can also rewrite errors in multiple errors by using the `AggregateError` class:

```csharp
services
    .AddGraphQLServer()
    .AddQueryType<Query>()
    .AddErrorFilter<AggregateErrorFilter>();

public class AggregateErrorFilter : IErrorFilter
        {
            public IError OnError(IError error)
            {
                return new AggregateError(
                    error.WithCode("A"),
                    error.WithCode("B"));
            }
        }
```

You can register as many error filters as you please, and they will form a chain of responsebility.

**Comment by kou-h** [comment]
Thank you . Then I want to return such an error. What needs to be done. Can you implement it with the above code?
HttpCode:220(custom)
{
    "error_code": "18513",
    "error_message": "XXXX"
}

**Comment by michaelstaib** [comment]
That is not a GraphQL spec compliant error. The error filter will allow you to rewrite GraphQL spec-compliant errors which will be in the following structure:
https://spec.graphql.org/June2018/#example-fce18

On top of that, you can control the status codes with the `IHttpResultSerializer`. Inherit from DefaultHttpResultSerializer and override GetStatusCode to take control over the status codes.

As mentioned above we are following the GraphQL over HTTP spec for the transport layer:
https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md

**Comment by kou-h** [comment]
Thank you .

**Comment by ntziolis** [comment]
>As mentioned above we are following the GraphQL over HTTP spec for the transport layer:
@michaelstaib First off I want to say great work on bringing graphql to dotnet and you are 100% correct that hot chocolate complies with the spec. We did run into an unexpected situation in regards to failed mutations though, since they did return a 500. 

While the spec does not specify what the return type of a failed mutation should be. Clients like the apollo-angular etc. do expect a 2xx otherwise they raise an exception (this is the default behavior of angulars http client). We used a custom serializer to mitigate this and return a 200

This was very surprising and cost us about 2 dev days to figure out as we initially suspected the dotnet web api pipeline to get in the way.

>If the response has Content-Type GraphQL and has a non-2xx status code, the data entry must be either:  

This means, the response code can only NOT be 2xx if these conditions (omitted) are met. But it does not prohibit returning 2xx even in those cases. So if HotChocolate returns a 2xx for valid query / mutation it is still spec compliant.

Some background:
I'm coming from the graphql node world and have contributed to graphql-tools / mesh etc. I have never come across any of the usual suspect node graphql servers or projects like hasura returning anything other than a 2xx for valid queries / mutations. I think the reasoning for this is since errors are provided in a strctured manner already there is no need to leverage http status codes on top in these cases (valid queries / mutations).

While again hot chocolate is spec compliant, based on the above would you consider changing the current behavior to be in line with what seems to be the "convention" in other frameworks?

Again fantastic work on this framework, I didn't think doing grpahql in dotnet could be fun, you changed my mind! :)

**Comment by michaelstaib** [comment]
We had discussions on this in the GraphQL Workgroup, and the general guideline is that:
- 2xx => data is set (there still are errors allowed if data exists or is not null)
- 4xx => data is not set ... GraphQL validation failed
- 5xx => no result was produced, only errors

This guidance initially came from Lee Byron at the meeting. There might be implementation variations in the wild like Apollo since, in the beginning, this was guidance and not spec text. 

> I think the reasoning for this is since errors are provided in a strctured manner already there is no need to leverage http status codes on top in these cases (valid queries / mutations).

This is not really the reasoning behind this. Moreover, providing the status code will let network infrastructures like WAFs and other things better handle and group requests. Otherwise, such components would need to parse the payloads in order to find out that your system is experiencing fatal errors. 

Further, if you run into such errors that wipe out your full request, there must be an issue with the implementation in the first place. Usually, with mutations, you would expose user errors on the payload. GraphQL errors are for developers and signal that a downstream service like the database fails. There is a good blog post on error handling by Marc-Andre, who worked at Shopify, GitHub, and now Netflix. He also likes me sits on the GraphQL technical steering committee, so he knows his GraphQL :)

> "Top-Level" Errors are today generally accepted as a way to represent "exceptional" errors and errors that are developer-facing. [Lee Byron] makes that clear in a few comments on the GraphQL-Spec repository.

https://productionreadygraphql.com/2020-08-01-guide-to-graphql-errors

Hot Chocolate lets you very easily opt into Stage 6a with the new Mutation conventions:
https://chillicream.com/docs/hotchocolate/defining-a-schema/mutations/#conventions

But you can also always change our default behavior by providing a custom `IHttpResultSerializer`. For this inherit from `DefaultHttpResultSerializer` override `GetStatusCode(IExecutionResult result)` and handle the status code by yourself.

```csharp
services
    .AddGraphQLServer()
    .AddHttpResultSerializer<MyCustomHttpResultSerializer>()
    ....
```

**Comment by ntziolis** [comment]
Wow, I much appreciate the detailed response and will take some time to read up on the info you provided.

If I think further about it the issue with the Apollo angular correct really isn't the Apollo current but the underlining angular http Client euch usually returns an observable with the response data simply but throws exceptions for 4xx and 5xx responses instead.

I will have a look if it matters sense to override this behavior when the client is used with a graphql server following the convention you mentioned.

I do update this thread with what we found to assist anyone running into this.

Thanks again for the info!

**Comment by andreamorello93** [comment]
What about Queries? if a rise an handled exception during the execution of the query i get 500
