### ISSUE TITLE
Type extensions are not working correctly with `.UsePaging()`, `.UseFirstOrDefault()` or `.UseSingleOrDefault()`

### ISSUE THREAD

**Issue by anasazy** [ChilliCream/hotchocolate#4590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Multiple type extensions for the same class are not working correctly when using `.UsePaging()`, `.UseFirstOrDefault()` or `.UseSingleOrDefault()`. Only the latter one registered in the `Startup.cs` or `Program.cs` file will work as expected.

For example using `.UsePaging()` for e.g. `Query.articles` should transform the output type from `[Article!]!` into `ArticleConnection` while using `.UseFirstOrDefault()` on `Query.article` should transform the output type from `[Article!]!` into Article.

For another examples what these methods are doing, just checkout the [MongoDB Integration in the documentation](https://chillicream.com/docs/hotchocolate/integrations/mongodb).

### Steps to reproduce

I've create a [Demo project](https://github.com/anasazy/hc-bug-demo) to demonstrate this bug. This demo project contains two main types: Article and Customer. While the Customer part is working as expected, Article doesn't. If you swap the type extension registration (`.AddTypeExtension<ArticleQueryTypeExtension>()` and `.AddTypeExtension<CustomerQueryTypeExtension>()` in the `Program.cs` file), you will see, that only the latter one is working correctly.

### Relevant log output

```shell
There is no error message or log output available.
```

### Additional Context?

<img width="1189" alt="Screenshot 2021-12-22 at 22 39 22" src="https://user-images.githubusercontent.com/765092/147158706-7d8929a0-893b-4bf7-bb7f-f5139cc85ec4.png">

### Product

Hot Chocolate

### Version

12.4.1

**Comment by tobias-tengler** [comment]
I don't think this is a fault with the data middleware, rather that a second `ObjectTypeExtension<T>` is not correctly registered. You can easily test this by adding an entirely new field to both extensions and confirming that only the field on the first type extension is added to the schema: `descriptor.Field("ext1").Resolve(0);`.

This doesn't solve your issue, but I hope you don't mind me asking, why are you using type extensions with a central query class (partial record)? For me personally this defeats the purpose of type extensions. You already define the resolvers in your partial query type without the middleware, why not make this partial record (why is it a record btw?) an Annotation-based type extension and also specify the data middleware via attributes? To me it feels like an unnecessary mix of Code-first and Annotation-based.

This doesn't change the fact that what you are experiencing is undocumented / unexpected behavior, but I just wanted to give my 2ct on the example.

**Comment by anasazy** [comment]
This is just a simple demo to demonstrate the bug. In the main project were I ran into that issue the first time, we have a couple of requirements. One of these is, that the code has to be organized in a domain driven way. Also we don't want to mixup model logic and HT type configuration logic. So, the Annotation-based way is not an option, but Code-first is (because you have separate files).

To fulfil the DDD requirement, we split up the `Query` class into separate partial Query classes for each domain. This way, each domain has it's own file to define resolver methods like `GetArticle()` and `GetArticles()`.

To fulfil the second requirement, we are using `ObjectType<T>` classes. But because you can't have multiple `QueryType` classes (which inherits from `ObjectType<Query>`), we thought, type extensions could be the solution. And it works... **EXCEPT** the fact, that `.UsePaging()` only works halfway. As described [in the documentation](https://chillicream.com/docs/hotchocolate/fetching-data/pagination), it adds all related arguments (`first`, `after`, `last` and `before`) correctly, but doesn't transform the output type into a Connection type as well. Similar problem with `.UseFirstOrDefault()` and `.UseSingleOrDefault()` which should transform the schema type from e.g. `[Object!]!` into `Object`.

You might wondering why returning an `IEnumerable<T>` even for the GetOne resolver. Well, in the main project we are using the MongoDB integration. And as you can see in the [documentation](https://chillicream.com/docs/hotchocolate/integrations/mongodb/#mongoexecutable), query resolver methods have to return `IExecutable<T>` which is interpreted in the schema as something like `[Object!]!`. To *fix* this you can use either `UseFirstOrDefault()` or `UseSingleOrDefault` (more about this [here](https://chillicream.com/docs/hotchocolate/integrations/mongodb/#firstordefault--singleordefault)).

I hope this helps to better understand the context.

**Comment by tobias-tengler** [comment]
Why does the Annotation-based approach conflict with your second requirement? You already have your repository which is decoupled from Hot Chocolate. The resolvers you define in the partial record are already sort of part of the "Hot Chocolate world". In the sense that they are "unclean" for example due to the usage of `[Service]`. If you were to move this file into a project without a Hot Chocolate package reference it wouldn't build. 

In our project we also have a clean cut between business logic and Hot Chocolate type configuration. We use Code-first to define the Types, while keeping the actual models clean. For Query resolvers and additional fields on these Code-first Types we use the Annotation-based approach. We are already working on code that is only relevant for Hot Chocolate, so using Code-first is only unnecessary boilerplate in a sense. If you can I would recommend you just try it out in your sample project. Make the partial record into just a clasd and name it like your files, e.g. ArticleQueryResolvers then annotate it with the [ExtendObjectType(OperationTypeNames.Query)] attribute and use the data middleware as attributes for the resolvers. You can then get rid of the Code-first Type Extension.

That being said I'll take a look at why the data middleware might not be working with your Code-first Type Extensions :)

**Comment by anasazy** [comment]
I have to admit, the approach you've suggested seems to fit our needs much better. I've try it out for my demo project and it works great. I think I'll create a PoC for our main project and discuss this with the team next.
