### ISSUE TITLE
Auto generate schema.graphql on server startup

### ISSUE THREAD

**Issue by nloum** [ChilliCream/hotchocolate#4640]
### Is your feature request related to a problem?

I want to write my generated HotChocolate schema.graphql file to a particular folder when I run my server in development mode. That way I don't have to remember to run `dotnet graphql update` every time I make a schema change.

### The solution you'd like

I tried something like this:

```
public class MyCodegenWorker : IHostedService {
	private readonly ISchema _schema;

	public MyCodegenWorker( ISchema schema ) {
		_schema = schema;
	}

	public Task StartAsync( CancellationToken cancellationToken ) {
		File.WriteAllText( "schema.graphql", _schema.ToDocument(  ).ToString() );
		return Task.CompletedTask;
	}

	public Task StopAsync( CancellationToken cancellationToken ) {
		return Task.CompletedTask;
	}
}
```

The important part is that I'm injecting an `ISchema` here. If I run this code right now I get this error:

```
Cannot resolve parameter 'HotChocolate.ISchema schema' of constructor
```

### Product

Hot Chocolate

**Comment by tobias-tengler** [comment]
From my understanding there isn't a single `ISchema` in the DI container, since your server could have potentially multiple schemas.
You need to resolve an executor for a specific schema (in your case likely the default one) and access the schema through it.

```csharp
var executorResolver = builder.Services.GetRequiredService<IRequestExecutorResolver>();
var executor = await executorResolver.GetRequestExecutorAsync(); // the name of a specific schrma can be used as an argument
var schemaText = executor.Schema.ToString();
```

In your example you could inject the `IRequestExecutorResolver` via the constructor. Personally I wouldn't create a hosted service and just perform this action directly from the `Main` method.

I'm closing this for now, feel free to re-open if you have further questions. :)

**Comment by nloum** [comment]
Thank you, this is exactly what I needed!
