### ISSUE TITLE
Enum without  the value 0 getting error

### ISSUE THREAD

**Issue by Gowtham-stack** [ChilliCream/hotchocolate#4679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If an enum value doesn't start with 0 then I'm getting this error

```json
{
  "errors": [
    {
      "message": "Frequency cannot serialize the given value.",
      "locations": [
        {
          "line": 23,
          "column": 5
        }
      ],
}
```

This is the enum

```csharp
    public enum Frequency
    {
        Daily = 1,
        DayOfArrivalOnly
    }
```
    
But if it starts with a value 0 then I'm not getting this issue. Eg.
    
```csharp
    public enum Frequency
    {
        None =0,
        Daily = 1,
        DayOfArrivalOnly
    }
```

### Steps to reproduce

1. Create an Enum without 0 index. Eg 
```csharp
    public enum Frequency
    {
        Daily = 1,
        DayOfArrivalOnly
    }
```
2. Then Query an Object which is having that enumeration property.

### Product

Hot Chocolate

### Version

12.5.0

**Comment by michaelstaib** [comment]
Can you post a repro?

**Comment by Gowtham-stack** [comment]
U mean "Steps to reproduce"? 
Ok, I updated it.

**Comment by Gowtham-stack** [comment]
Team, This is my class structure
```
    public class RoomType 
    {
        public Frequency FeeFrequency { get; set; }
    }
```
In my Db, some of the `RoomTypes ` having `FeeFrequency `  value as 0.  
When graphql queries roomType, it tries to convert 0 to enum (FeeFrequency type). 
But there is no index value 0. That's why I'm getting this issue. 
I have a workaround for this issue.
Its my bab, I guess this is not a bug, maybe we can close this bug

**Comment by benmccallum** [comment]
Does seem like it's a C# thing that `default(EnumWithNoZeroMember)` returns `0`, and the type is the enum type which is fun!
Source: https://stackoverflow.com/questions/4967656/what-is-the-default-value-for-enum-variable
Runnable example: https://dotnetfiddle.net/IuZXRs

My advice would be to avoid them 😜, perhaps adding an `Unknown = 0` where you have to.

Not sure there's anything that can be done in Hot Chocolate, because I'm guessing you're trying to return the instance of a type without setting the enum property to a non-default value, so the value is `0` of type `EnumWithNoZeroMember` and it's struggling to serialize that. Enums are represented in GraphQL via the member name, and there is none in this case, so it'd break.

```c#
public enum EnumWithNoZeroMember
{
    Foo = 1,
    Bar // = 2
}

public class Booking
{
    public EnumWithNoZeroMember Status { get ; set; } // A.K.A. = default(EnumWithNoZeroMember); 
}

public class Query
{
    public Booking GetBooking() => new Booking();
}
```

**Comment by benmccallum** [comment]
Ah, just saw your comment about it being bad data in the db, so the callstack is erroring in your data access layer not when graph tries to serialize/return the response? Hmm, yea that's your end. Maybe making the column nullable and setting all `0` to `null` is more what your database should look like.

**Comment by Gowtham-stack** [comment]
Thanks @benmccallum , I changed the column to nullable and make `0 ` to `null `, Now everything works fine. Thanks 

> Ah, just saw your comment about it being bad data in the db, so the callstack is erroring in your data access layer not when graph tries to serialize/return the response? Hmm, yea that's your end. Maybe making the column nullable and setting all `0` to `null` is more what your database should look like.
