### ISSUE TITLE
OAuth/Authorization configuration for BCP

### ISSUE THREAD

**Issue by niklashjh** [ChilliCream/hotchocolate#4692]
### Is your feature request related to a problem?

It seems like it's not possible to configure default authorization configuration values in the BCP middleware.

![image](https://user-images.githubusercontent.com/66720563/151310792-de61b6b8-8716-4ed6-8b88-5dcd96fa8923.png)

### The solution you'd like

Being able to set these values in GraphQLToolOptions or manually editing bcp-config.json

### Product

Banana Cake Pop

**Comment by nikolai-mb** [comment]
As someone who migrated from swagger UI to banana cake pop, i find this to be the biggest limitation in my workflow.
I usually open new documents to quickly test queries, and since authentication has to be configured for each new document (OAuth2, implicit), this quickly becomes a nuisance. Swagger allows the authorization options to be fre-filled in the UI, so all a developer has to do, is to click authorize. Having something similar for BCP would be incredibly helpful

**Comment by michaelstaib** [comment]
We are working on something in this regard ...

**Comment by rstaib** [comment]
This is one of our top priorities and will be addressed in one of our next releases. Thank you for sharing 👍🏻

**Comment by zyofeng** [comment]
Any progress on when this will be released?

Migrating from NSwag/Swashbuckle I might it very stressful having to code the authorize/token endpoints and scopes required.
