### ISSUE TITLE
About subscription, how to access message of type: "connection_terminate" and type: "complete" on StrawberryShake

### ISSUE THREAD

**Issue by CoreDX9** [ChilliCream/hotchocolate#4804]
### Is your feature request related to a problem?

How to access message of type: "connection_terminate" and type: "complete" on subscription by StrawberryShake. Then I can dispose subscription when server complete stream or close connection.

And Banana Cake Pop will run subscription whether server complete stream or close connection. Then I can't stop subscription (Nothing will happen when click cancel button) if server complete stream or close connection.

### The solution you'd like

I don't know if there is a solution.

### Product

Strawberry Shake

**Comment by michaelstaib** [comment]
In order to close the connection in strawberry shake you need to dispose the subscription. 

A good pattern here is to use our DataComponent in blazor which allows you to register the subscription with the component and when the component is disposed the subscription will be as well.

But from the description, it sounds that you actually did not correctly implement subscriptions in the backend. Make sure to correctly handle cancellation tokens in the backend so that the stream can be terminated.

**Comment by CoreDX9** [comment]
I'm sure to correctly handled cancellation tokens in the backend. I mean, when I call `eventSender.CompleteAsync("some_topic");` on server, how can I know subscription stream was completed and websocket connection was closed. I saw complete message and connection closed on DevTools. But client never notify me stream has terminated.

code like
``` csharp
var watcher = MyClient.OnNewMessage.Watch();

var subscription = watcher
    .Subscribe(res =>
    {
        Logger.LogInformation("New message: {0}", res);
    },
    ex => Logger.LogError(ex, "Exception happened."),
    () => Logger.LogInformation("Stream completed."));
```

`ex => Logger.LogError(ex, "Exception happened.")` only will be called when I call `subscription.Dispose()`. It will not be called 
when I call `eventSender.CompleteAsync("some_topic");`. `() => Logger.LogInformation("Stream completed.")` is similar to previous one.

![屏幕截图 2022-03-03 072306](https://user-images.githubusercontent.com/26616055/156467134-158dc71a-6c87-46be-9cfe-73abcfc2d2c4.jpg)
