### ISSUE TITLE
Access to remote schema response headers and contextData info in Gateway

### ISSUE THREAD

**Issue by Sangeetha-Murugesan** [ChilliCream/hotchocolate#4809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a gateway that stitches a remote and local schema. I need to access response header and contextData from a remote call. But I couldnt get any other remote info in gateway. 

To achieve this ,we tried to implement the same as mentioned in this issue [https://github.com/ChilliCream/hotchocolate/issues/679](url) but couldnt use "IHttpQueryRequestInterceptor" class.What is the namespace to access this interface or is this deprecated,if yes what would be the alternative for this interface

Also I tried to access remote schema result using "IHttpStitchingRequestInterceptor" which is also not works, OnReceivedResultAsync() is not even called. Is there another solution to access the remote schemas info?

### Steps to reproduce

1.  I have added this in my startup : 
 
            ` services.AddSingleton<IHttpStitchingRequestInterceptor,StitchingInterceptor>();`

2.This is my StitchingInterceptor class 
    
   ```
 public class StitchingInterceptor : IHttpStitchingRequestInterceptor
    {
        public ValueTask OnCreateRequestAsync(NameString targetSchema, IQueryRequest request, HttpRequestMessage requestMessage, CancellationToken cancellationToken = default)
        {
            return new ValueTask();
        }

        public ValueTask<IQueryResult> OnReceivedResultAsync(NameString targetSchema, IQueryRequest request, IQueryResult result, HttpResponseMessage responseMessage, CancellationToken cancellationToken = default)
        {
            Console.Write("In Stitching Interceptor");
            return new ValueTask<IQueryResult>(result);
        }
    }

```

### Product

Hot Chocolate

### Version

13 preview

**Comment by Sangeetha-Murugesan** [comment]
@tobias-tengler  Any update on this?

**Comment by michaelstaib** [comment]
you are looking for this:
https://github.com/ChilliCream/hotchocolate/blob/main-version-12/src/HotChocolate/Stitching/src/Stitching/Pipeline/HttpStitchingRequestInterceptor.cs

which is around since version 8.

```
public ValueTask<IQueryResult> OnReceivedResultAsync(
            NameString targetSchema,
            IQueryRequest request,
            IQueryResult result,
            HttpResponseMessage responseMessage,
            CancellationToken cancellationToken = default)
```

you can take the headers from the response message and store them on the context data from the result.

you essentially use `QueryResultBuild.FromResult` to create a result builder from the current result. Store the response header that you need on the context data and create the new result with the builder and return it.

The context data that you put into the result will be copied into the resolvers scoped context data. So you are able to access these in the subtree that is being resolved.

`IResolverContext.ScopedContextData`

**Comment by michaelstaib** [comment]
Also, this is not a bug. Creating bugs for questions is really just clogging up our system. Best to just either open a discussion and ask or join us on https://slack.chillicream.com.
