### ISSUE TITLE
Error parsing the multipart / file upload request

### ISSUE THREAD

**Issue by vavalomi** [ChilliCream/hotchocolate#4837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Server fails to process (properly formed) multipart/form-data request. The problem seems to be triggered by the double line break (\r\n\r\n) in front of the file content. Adding extra line breaks around operations and map sections seems to work just fine.

### Steps to reproduce

Content-Type: multipart/form-data; boundary=boundary
\r\n
--boundary
Content-Disposition: form-data; name="operations"
\r\n
query json
\r\n
--boundary
Content-Disposition: form-data; name="map"
\r\n
{ "0": ["variables.file"] }
\r\n
--boundary
Content-Disposition: form-data; name="0"; filename="filename.zip"
\r\n
\r\n
filename.zip content
--boundary--

### Product

Hot Chocolate

### Version

12

**Comment by tobias-tengler** [comment]
We're using ASP.NET Core's [FormFeature](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.features.formfeature) to parse the multipart request body: https://github.com/ChilliCream/hotchocolate/blob/9d7abcfcdda4e129d3908476cf83c9376f27fb1d/src/HotChocolate/AspNetCore/src/AspNetCore/HttpMultipartMiddleware.cs#L72-L73

Skimming the multipart spec, it talks about "a" line - not multiple, so I don't think your multipart request is actually valid:

> The body must then contain one or more body parts, each preceded by a boundary delimiter line, and the last one followed by a closing boundary delimiter line. After its boundary delimiter line, each body part then consists of a header area, a blank line, and a body area.

[Reference](https://datatracker.ietf.org/doc/html/rfc2046#section-5.1)

I'm closing this issue, since I don't believe there's anything we can do about it, but please get back to us, if it turns out to be an issue on our side :)

**Comment by vavalomi** [comment]
I kinda read the same document (similarly skimming :)) but found the mentioning of the double break on page 19:

> The boundary delimiter MUST occur at the beginning of a line, i.e.,  following a CRLF, and the initial CRLF is considered to be attached to the boundary delimiter line rather than part of the preceding part.  The boundary may be followed by zero or more characters of linear whitespace. It is then terminated by either another CRLF and the header fields for the next part, or by t**wo CRLFs**, in which case there are no header fields for the next part.  If no Content-Type field is present it is assumed to be "message/rfc822" in a "multipart/digest" and "text/plain" otherwise.

The client code is in python and uses requests package, which is not exactly ASP.NET but also 'almost' standard tool ...

I did further digging and it seems that sometimes two line breaks are also fine, and this depends on the contents of the operations and maps json objects. I'm not manually forming the query body so it comes with the list of fields delimited by \n instead of commas. So if I remove those new lines, the request goes through, even if there are double breaks.

I guess I have a (non-elegant) solution, but wander how many other clients of our API service will step into the same issue...

**Comment by tobias-tengler** [comment]
I think what you linked still just applies to the boundary and not for the headers, as I also discovered and noted in my initial response.

That being said, I think the real issue here is that your data should use CRLF as the line break style and then it should go through.

To reiterate, we are using the official ASP.NET Core multipart parser and everything works fine with multipart requests sent via the fetch browser API or the .NET HttpClient. I think this is most likely an issue with your client library or malformed data. I hope using CRLF for your data will help you solve the issue :)

**Comment by vavalomi** [comment]
Thanks a lot. In addition to implementing in python, I was trying the same in Insomnia, as well as REST client in vscode. And I was able to generate errors when introducing line breaks in different places. Both tools (seem to) sanitize user input before sending out so cannot be exactly sure how the raw request body looked like. It is definitely not related to the file content itself, just how to form parts are structured.

So introducing the line breaks does cause errors but I agree with you that it's not perfectly clear whether those breaks are part of the standard or not and whether my python was breaking for the same reason or not.

After going back to my actual code, and making sure that there are no 'unnecessary' line breaks introduced, everything seems to work, so I guess this means that it works without any need for 'special' treatment. 

Therefore the issues is rightly closed.  Thanks again!
