### ISSUE TITLE
Breaking changes when upgrading HotChocolate from 12.4 to 12.5+

### ISSUE THREAD

**Issue by jblazek** [ChilliCream/hotchocolate#5145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are currently using v12.4.1 and ran into issues with breaking changes when migrating the later v12.x minor versions.

Specifically, the `SchemaSyntaxSerializer`, `DocumentWriter` and other types were present in [12.5.0-preview.21](https://github.com/ChilliCream/hotchocolate/tree/12.5.0-preview.21/src/HotChocolate/Language/src/Language/Legacy/Visitors/Obsolete), but removed in [12.5.0.preview.22](https://github.com/ChilliCream/hotchocolate/tree/12.5.0-preview.22/src/HotChocolate/Language/src/Language/Legacy/Visitors/Obsolete). 

The breaking change in a minor version upgrade is causing extra effort to rework compatibility and also the upgrade path is not clear in regards to how the new types should be utilized.

Is there documentation or an upgrade guide on this version upgrade? Keeping breaking changes only in major version upgrades will help consumers know how they can upgrade in a compatible way.

Additionally, it looks like the [PublicAPI.Shipped.txt](https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Language/src/Language/PublicAPI.Shipped.txt) in main shows the old types as present, even though they've been gone a while. This file doesn't seem to be getting updated correctly.

### Steps to reproduce

1. Use the SchemaSyntaxSerializer type in v12.4.1
2. Upgrade to a later version of 12.5+
3. Compilation fails because the types are gone

### Product

Hot Chocolate

### Version

12.4.1

**Comment by michaelstaib** [comment]
Yes, this was done in error but was discovered too late. We are looking at a better way at the moment to spot binary incompatibilities. We used to use the Roslyn analyzer form the ASP.NET core team which worked well on Windows with Visual Studio. But our team works only on macOS or Linux and there they had a lot of issues. But this has a high priority for us and we are investigating at the moment tooling to guard against future binary compatibility issues in minor version changes. 

Sorry for the inconvenience here.

To get the GraphQL SDL just do `schema.ToString()` also on the syntax tree you can do `syntaxNode.ToString()`.

**Comment by michaelstaib** [comment]
Closing this issue since this is known and we are working on solutions to not run into such issues in the future.

**Comment by AlilNinja** [comment]
This issue shouldn't be closed yet as it's only partially answered. We still need documentation or an upgrade guide on how to switch from the `SchemaSyntaxSerializer` and `DocumentWriter` to the "new schema printer".

Our issue with the breaking change isn't how to get the schema (we're already calling `schema.ToString()`), our issue is that we use both the `SchemaSyntaxSerializer` and `DocumentWriter` and they no longer exist. Specifically, we have a `_Service` endpoint that we use for Apollo Federation. In order to get the schema that this endpoint returns, we have a class that inherits from the `SchemaSyntaxSerializer` and overrides various `VisitXDefinition` functions, and we use those overridden functions to skip certain parts of the schema from being visited. 

What we use is something like this:

```
public string Serialize(ISchema schema)
{
	var schemaBuilder = new StringBuilder();

	using (var writer = new StringWriter(schemaBuilder))
	using (var documentWriter = new DocumentWriter(writer))
	{
		DocumentNode node = SchemaSerializer.SerializeSchema(schema);
		_walker.Visit(node, documentWriter);
	}

	return schemaBuilder.ToString().Trim();
}
```
the `_walker` class above is the one that's using the `SchemaSyntaxSerializer`, and it uses it for methods like this:
```
protected override void VisitDirectiveDefinition(DirectiveDefinitionNode node, DocumentWriter writer)
{
	if (!IsFederationDirective(node))
	{
		base.VisitDirectiveDefinition(node, writer);
	}
}
```

The only thing we have to go off of for upgrading is a message that says `"This is replaced by the new schema printer"`. As far as we can tell, there's no documentation on how to transition from the `SchemaSyntaxSerializer` and `DocumentWriter` to that new schema printer though, or even how to _use_ the new schema printer in general. Is there any documentation you can provide for that?
