### ISSUE TITLE
HotChocolate.ApolloFederation support for AspNetClassic

### ISSUE THREAD

**Issue by Arrivegrsmith** [ChilliCream/hotchocolate#5355]
### Is your feature request related to a problem?

I'm unable to recommend HotChocolate for company wide adoption due to legacy applications being in .NET 4.7 and the critical requirement of Apollo Federation support. The HotChocolate.ApolloFederation NuGet only supports .NET Core applications.

We _are_ using Microsoft.Extensions.DependencyInjection in .NET 4.7 which may help your implementation. (https://arjanvanbekkum.github.io/blog/2019/12/31/Dependency-Injection-Managed-Identity-Net472)

### The solution you'd like

Either a hack to get us up and running with HotChocolate **with** Apollo Federation in our legacy .NET 4.7 applications or an update to the NuGet to support ASP .NET 4.7. **OR** commentary on a timeline.

We'll likely need to use the GraphQL NuGet in the meanwhile since we're on a very fast timeline.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
We have dropped support for .NET Framework Classic with Hot Chocolate version 10 mainly due to the lack of interest form our community.

The Hot Chocolate core in general is still compatible with .NET Standard 2.0, so you could theoretically create your own transport layer.

Regarding Apollo Federation support, for newer features, which includes Apollo Federation V1 and V2 we only support newer .NET Core based versions.

At this point we do not plan to bring anything to .NET Framework anymore. What you can do is use our Fusion Gateway to wrap your old infrastructure instead of building on top of it.
