### ISSUE TITLE
CSV response support

### ISSUE THREAD

**Issue by enerdev2022** [ChilliCream/hotchocolate#5357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is not really a bug, but there was no better "question" category available, apologies.
Does Hot Chocolate support, optionally, serving responses as CSV?
My understanding, based on research so far, is that it goes against the purpose of GraphQL (even outside of Hot Chocolate or even .NET).
I still need to make it work though, for reasons outside of my control, so I am thinking of going the middleware route (converting GraphQL JSON responses into CSV based on a flag query argument).
I would be happy even with a yes / no sort of answer from a Hot Chocolate expert, thank you. Though any tips are always very welcome!

### Steps to reproduce

1. Search the documentation / internet for available CSV output ideas / solutions.
2. Find nothing directly relevant.

### Product

Hot Chocolate

### Version

11.x.x

**Comment by enerdev2022** [comment]
And a subsequent question, do I have a chance to plug into the response pipeline earlier rather than later to avoid parsing JSON?

**Comment by tsinghammer** [comment]
Hi, can you tell what the use case of this is?
One power of GraphQL is that it returns structured/hierarchical data, and I don't know how one would represent hierarchical data in a CSV format.
You can of course have a field in your graph that returns a string cointaining the CSV data.

**Comment by enerdev2022** [comment]
Hi @tsinghammer , the use case is being able to download results of any query (supporting future queries automatically) in the CSV format without forcing that work on client code. The output would be simply flattened (like a graph can be denormalized into a table, ignoring any loops/recursion/column-naming/nested-array issues etc.). It's important to understand that my scenario is a misuse of the technology. Solution I am going for at the moment (and it's working) is using ASP.NET Core middleware which, when a query argument flag is set, parses the original GraphQL response into JSON and then flattens that into a CSV and then sets the response content type and disposition to be a CSV attachment. Upside - it fulfils the requirement, downside - it's clearly a workaround. I was just wondering whether there is a better approach (without questioning the requirement itself or handing conversion work over to code outside of the API). I am also looking for some confirmation, that this is an unnatural thing to expect from GraphQL natively and there is no handy plug-in package waiting for me to discover it.

**Comment by tsinghammer** [comment]
Thanks for the explanation @enerdev2022 ! I'm not too deep into HC, but I don't think this can be offered out of the box.
To have a generic solution it would require at least the possibility to provide a custom projection to flatten the result, since there may be naming collisions.
I would have thought of the same solution you implemented, be it a middleware or a small separate service and wouldn't consider it as a workaround, since the conversion to CSV is probably something customized. 
With version 13 the execution pipeline will become more flexible.
But maybe someone here with deeper knowlegde can say something in this regard.

**Comment by michaelstaib** [comment]
Please post questions to GitHub discussions or to our slack channel... 

Since this is clogging up our resources on managing real issues.

<img width="1198" alt="Screen Shot 2022-08-31 at 11 31 41 PM" src="https://user-images.githubusercontent.com/9714350/187788935-61074ba1-97db-4e33-b2fb-e29d72055c18.png">
