### ISSUE TITLE
Support for Resource-based authorization?

### ISSUE THREAD

**Issue by zivfuture** [ChilliCream/hotchocolate#5442]
### Is your feature request related to a problem?

Resource-based authorization  is more  reasonable then Policy-authorization,

For example:  Iike [Shiro](https://shiro.apache.org/)  ,  Casbin   and so on .

Resource-based authorization  is more clearly and easy to  maintenance

Hotchocolate is great project,   can we support Resource-based authorization?

### The solution you'd like

```c#
public interface IPermission
{
    string Permission { get; set; }
}

[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
public class PermissionAttribute : Attribute, IPermission
{}

public class Query
{
    //query operation
    [Permission("User.View")]
    public User Search(int id){...}
}

public class Mutation
{
    //mutation operation
    [Permission("User.Update")]
    [Permission("User.Edit")]
    public User Update(User user){...}
}


//request:
{
  User(id:2){
      id
      name 
      sex
  }
}

//Authorization middleware( by custom  or by any intercepter new?):
public async Task Invoke(HttpContext context, ...)
{
   //find current visiter from accesstoken
    var currentUser=claimsPrincipal.FindFirstValue(ClaimTypes.Sub); 
   //find permissions from cache by current visiter
    var permissions=findFromRedis(currentUser);

   //important,  for the request above this will get  permissions attribute : "User.View", for now i can't get the custom permission attributes 
   var permissionRequired=find Attributes from current operations(Query/Mutation),  
   //do permissions check....
}
```

### Product

Hot Chocolate

**Comment by zivfuture** [comment]
#3456

**Comment by hsluoyz** [comment]
@zivfuture you can try Casbin, it has a .NET version: https://github.com/casbin/Casbin.NET

Casbin is also widely used in GraphQL scenarios: https://casbin.io/docs/graphql-middlewares, it will be easily to adapted to our scenario.

**Comment by michaelstaib** [comment]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/9714350/193222257-10d4ce80-34a3-43c6-9334-976dd30c27a0.png">

**Comment by michaelstaib** [comment]
Best Practice is: It should live in your business logic ... not on the GraphQL layer.

**Comment by michaelstaib** [comment]
We will rework authorization for some of the next 13 dot releases. For now I will close this issue.

**Comment by glen-84** [comment]
@michaelstaib,

Could we please reopen this issue?

1. It may be a best practice, but developers don't always follow best-practices, and HC already supports authorization in the GraphQL layer.
2. The current authorization system only allows the use of two properties, `Roles` and `Policy` – there is no clean way to specify other data like a resource name/type, action name, permission, etc. Would it be possible for the attribute and directive to store arbitrary data in a dictionary, for example? Then derived `Authorize` attributes could add data to that dictionary which would then be available in the `IAuthorizationHandler`.

**Comment by michaelstaib** [comment]
We will not change it. You already can do this with policys and there are no plans to change it further. If you want to add arbitrary data you could use the ContextData on the types system members. There are enough extension points for that approach. The core team does not plan any further changes to the authorization system as these are all high impact changes.

**Comment by glen-84** [comment]
> You already can do this with policys

Do you mean writing policies that execute an authorization check, or forcing resource/action or permission data into the Policy property?

For the former, it's not possible to pass arguments to a policy, so you'd either need a unique policy for each resource/action pair, or a single policy that extracts the resource/action data from somewhere.

For the latter, this is what I'm trying to avoid.

> If you want to add arbitrary data you could use the ContextData on the types system members.

I tried a few things, but I don't know how to do this. 😞

> these are all high impact changes

I don't see how adding one additional optional property is high impact. Would it affect performance to have a "state" dictionary on the directive?

---

I'm trying to access my own AuthorizeAttribute directly from the middleware context:

**Resolver:** context.Selection.Field.ResolverMember.CustomAttributes
**Object type:** context.Selection.Field.RuntimeType.CustomAttributes
**Field:** context.Selection.Field.Member.CustomAttributes

Maybe something like this could work, I just need a way to determine if the authorization request is for a resolver, object, or field.

**Comment by bbrandt** [comment]
@glen-84 Did you ever work out a way to simplify your resource-based authorization with Hot Chocolate?

**Comment by glen-84** [comment]
@bbrandt

I went with something in the "business/domain layer" instead, so that it applies regardless of how you access it (via GraphQL, REST, CLI, etc.).

I basically run all queries and mutations via MediatR, and authorization checks are handled in an `IPipelineBehavior`.

I'll paste the explanation that I sent someone else in case you find any of it useful.

---

Each MediatR command or query has a custom `Authorize` attribute that specifies a resource type as a generic argument, and an action name as an argument:

```cs
[Authorize<ArticleResource>(actionName: nameof(ArticleResource.Actions.DeleteArticle))]
public sealed record DeleteArticleCommand(long EntityId)
    : IRequest<long>, ISingleInstanceRequest<long>;
```

When the `AuthorizationBehavior` (`IPipelineBehavior`) runs, it accesses this resource type, and creates an instance of it.

The resource instance provides a name (f.e. `editorial:article`), an action name (f.e. `DeleteArticle`), and a list of "instances" (essentially just a list of `Dictionary<string, object>` with key/values that are relevant to authz (f.e. the ID of the article being deleted, or the ID of the article's owner).

That data is then available to be sent to an authz server or service.

Here is an example `ArticleResource`, which adds the ID of the article during construction (using a well-known property from the request -- `EntityId` [enforced using the `ISingleInstanceRequest` interface]). When instance data is requested (`GetInstancesAsync`), it iterates over the instances (which contain IDs/entity IDs) and uses an article repository to load the `Article` and access its "owner" user ID. Now the authz behaviour and server/service can also make decisions based on the owner of the resource/article (or any other value that you add to the instance data).

```cs
public sealed class ArticleResource : BaseResource
{
    public override string Name { get; } = "editorial:article";

    public enum Actions
    {
        DeleteArticle
        // ...
    }

    private readonly IArticleRepository? articleRepository;

    public ArticleResource(
        IArticleRepository articleRepository,
        ISingleInstanceRequest<long> request)
    {
        this.articleRepository = articleRepository;

        // Add the entity ID.
        this.Instances.Add(new() { { IdAttribute, request.EntityId } }); // IdAttribute = "id"
    }

    public ArticleResource(IBaseRequest request) : base(request) { }

    public override async Task<IList<Dictionary<string, object>>> GetInstancesAsync(
        CancellationToken cancellationToken)
    {
        if (this.articleRepository is not null)
        {
            foreach (var instance in this.Instances)
            {
                if (instance.TryGetValue(IdAttribute, out var id))
                {
                    var article = await this.articleRepository
                        .SingleByIdAsync(ArticleId.From((long)id), cancellationToken);

                    // Add the owner ID.
                    instance.Add(OwnedByUserIdAttribute, article.OwnedByUserId); // OwnedByUserIdAttribute = "ownedByUserId"
                }
            }
        }

        return this.Instances;
    }
}
```

(This example is for "single instance" requests, i.e. requests to add/edit/delete a single entity, but the resource type does support multiple instances [which you might use for something like bulk edit/delete mutations]).
