### ISSUE TITLE
StrawberryShake.Server generated files are not visible in Dependencies -> Source Generators

### ISSUE THREAD

**Issue by simonhoss** [ChilliCream/hotchocolate#5533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey

I'm using Rider

I created a new GraphQl client with StrawberryShake.Server, everything works like a charm and I can use the client, but the generated client is not visible in the Dependencies 
![image](https://user-images.githubusercontent.com/1117667/199978176-6839cc05-d4a7-4f08-ac14-135f6e8627e5.png)

It should look like this with the generated client inside
![image](https://user-images.githubusercontent.com/1117667/199978279-9843b7e4-48dd-4442-a826-2dbbabf0b8a2.png)

### Steps to reproduce

1. I followed the tutorial from here: https://www.youtube.com/watch?v=I0ihOcBVu8c

### Product

Strawberry Shake

### Version

13.0.0-preview.76

**Comment by michaelstaib** [comment]
Its not a source generator anymore. We had problems with source generators in combination with Blazor. Blazor in version 6 has become a source generator and as of now source generators cannot be pipelined. Since Blazor is our main target we have removed source generators and reimplemented it with a classical approach that is based on MSBuild. We will reevaluate the situation as source generators get pipelining support.

**Comment by simonhoss** [comment]
Got it. Thanks for your answer.
