### ISSUE TITLE
Subscriptions Documentation

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#580]

**Comment by TristanTDev** [comment]
Hi Michael, just wondering when this might be implemented? Currently trying to add subscriptions to my API but with no documentation it's nearly impossible to know how to define the resolvers etc.

**Comment by michaelstaib** [comment]
I am so sorry for this, had this on my mind for quite a while now. I will put some documentation together **tomorrow** for this. In the meantime have a look at our star wars example... it got subscriptions in it.

I will give you a ping once I have this in.

**Comment by TristanTDev** [comment]
Cheers thank you so much! I looked at the examples (No idea why I couldn't find that yesterday when looking through), got it working from that so that's perfect! Documentation would be excellent, but just me doing a "Man look" through the examples! 

Cheers for the quick response, no need to apologise, I'm just thankful for your code, so much nicer than the others I've used!

**Comment by michaelstaib** [comment]
I have published a draft now:
https://hotchocolate.io/docs/next/code-first-subscription
