### ISSUE TITLE
gRPC Support with .net core 3.0

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#602]

**Comment by michaelstaib** [comment]
Also worth looking into: https://en.wikipedia.org/wiki/Apache_Thrift

**Comment by michaelstaib** [comment]
https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.0

**Comment by jurby** [comment]
Hi, gRPC transport would be great as an add-on to Websockets, since gRPC is primarily designed for the HTTP2 protocol with the possibility of using multiplexing for multiple requests at the same time over one open client / server connection.
At the same time, for example, in a web project, it is not necessary to use another transport for GraphQL and another for realtime communication, unless I want to use Websockets technology or other fallback.

We are currently addressing this question for one project that has a global scale and is most concerned about latency + DNS + TLS + HTTP overhead for each request / response. This will be solved just by the grpc-web technology, which is not 100% ready over the full HTTP2 protocol, but this will be solved over time and currently limiting the streaming only from the server is enough for us.

Look here for some implementations:

- Rejoiner project / [graphql_service.proto](https://github.com/google/rejoiner/blob/7f18f8c6056cdb2f2cf54237b17856f08c794df4/examples/src/main/proto/graphql_service.proto)
- DFuse project / [graphql.proto](https://github.com/dfuse-io/graphql-over-grpc/blob/master/graphql/graphql.proto)

Thank you for your time and your work.

**Comment by michaelstaib** [comment]
@jurby thanks for your input. We will look into this for version 12.

**Comment by jurby** [comment]
> @jurby thanks for your input. We will look into this for version 12.

Thank you for your answer. It will be great. I will try to direct the use of grpc / grpc-web in the project that it would be made public as an extension eg `HotChocolate.AspNetCore.Grpc` or `HotChocolate.Grpc`. Would this namespace be suitable?

**Comment by michaelstaib** [comment]
HotChocolate.AspNetCore.Grpc

**Comment by jurby** [comment]
@michaelstaib Created draft for grpc support in project https://github.com/ChilliCream/hotchocolate/pull/1122. Please check if it's ok.

**Comment by tanekim77** [comment]
I think this will be a killer feature. grpc requires protobuf implementation. I believe the following library may help develop this feature faster:
https://github.com/protobuf-net/protobuf-net
