### ISSUE TITLE
The proper way to handle when there is one remote schema down while fetching all schemas to do stitching on the gateway.

### ISSUE THREAD

**Issue by x-Zyte** [ChilliCream/hotchocolate#615]
If there is one remote schema down while fetching all schemas to do stitching, the gateway will not work until fetching all schemas is completely done.

I would like to have the ability to skip the remote schemas which are down and continue to do the stitching and then continue processing the request and do the stitching for the remote schemas which are un-stitch yet in the next request.

**Comment by michaelstaib** [comment]
There are multiple questions that come to mind if we would implement such a behavior.

1. Since only part of the schema is online what would clients do that were written against the complete schema.

2. What would happen to queries if they depend on the missing parts?

The Hot Chocolate stitching gateway can also be reconfigured so that you provide the schemas on startup.

`builder.AddSchemaFromFile`

The gateway could then create a valid schema and queries that would touch the offline parts would fail with a GraphQL error.

**Comment by x-Zyte** [comment]
I would say for the query that would touch offline parts would fail by default, and vice verse, the query that would touch online parts would work as normally.

And for the “AddSchemaFromFile”, it’s quite tricky with my situation. I’m working on microservice stuff and right now I have GraphQL servers about 10, probably more in future, and each server has many fields in query and mutation. It looks like there is a lot of work to create schema file for all components. You know? haha 😆

**Comment by michaelstaib** [comment]
I think it would not be possible to implement something like this since the stitching server could not say if a field is missing do to a missing remote schema or if a type is missing do to remote schema or if one accidentally misspelled something.

We could not fulfill the spec validation rules any more.

The stitching server could handle that remote schemas are offline but only once it has initially resolved all remote schemas.

We are soon bringing out a schema registry which will basically hold all the schemas in your environment. The Microservices will be able to push their schemas to the registry on startup and the registry will be able to push the schema to the gateway. With this setup your Microservices will no longer need to be online at all times. 

This feature will come out with version 10 in about 8 - 10 weeks from now.

**Comment by michaelstaib** [comment]
I think the best way to solve your issue is to use our schema registry once we have implemented it. I will close this issue.

**Comment by x-Zyte** [comment]
Yeah, I see. Looking forward to it, thanks for the cool thing.
