### ISSUE TITLE
AuthorizeDirective does not deserialize roles property correctly if it is passed as a single string

### ISSUE THREAD

**Issue by eduleite** [ChilliCream/hotchocolate#624]
In the following schema, the roles will not deserialize correctly and will always be empty:

```
type Query {
	queryOne: String! 
	queryTwo: String! @authorize(roles: "ROLE1")
	queryThree: String! @authorize(roles: "ROLE3")
}
```

They will only deserialize properly if declared this way:

```
type Query {
	queryOne: String! 
	queryTwo: String! @authorize(roles: ["ROLE1"])
	queryThree: String! @authorize(roles: ["ROLE3"])
}
```

**Comment by michaelstaib** [comment]
The issue here is that we do not honor input coercion rules on directive arguments. I will write some tests so that we can track this issue. 

The directive itself should not have to deal with these rules so we have to have the inputs already correctly coerced when we pass the to the directive. 

I think we will create a fix with 9.0.0-preview.2 or 9.0.0-preview.3 at the end of this week.
