### ISSUE TITLE
Are nested mutations supported?

### ISSUE THREAD

**Issue by kongkong56** [ChilliCream/hotchocolate#634]
```GraphQL
user {
  id
  name 
  userinfo
}
userinfo {
  address
  phone 
}
```
so ,this nested mutation is support?

**Comment by michaelstaib** [comment]
Nested mutations are not supported by the GraphQL Spec itself. The GraphQL spec explicitly describes top level mutations. Moreover, the spec explicitly describes the algorithms to that. So, if we introduced such a feature we would produce a GraphQL endpoint that looks like GraphQL but does not act like it. 

Clients for instance like relayjs would have no clue that for instance the fields on the 3. level are actually write actions.

See also the spec:

> Because the resolution of fields other than top‐level mutation fields must always be side effect‐free and idempotent, the execution order must not affect the result, and hence the server has the freedom to execute the field entries in whatever order it deems optimal.

https://facebook.github.io/graphql/June2018/#sec-Normal-and-Serial-Execution

There a further sections describing in detail the various algorithms for the mutation and why it is executed serially, but I think this paragraph sums it up the best.

In order to stay compatible with other tools for GraphQL we opted to not implement this feature. If you want it still, a good way would be to go to the GraphQL spec repository and create an issue describing this feature.

https://github.com/facebook/graphql

As soon as a GraphQL feature reaches Draft status we will implement it.

**Comment by michaelstaib** [comment]
But your example does not even show a mutation... a nested mutation would look something like the following, right?

```GraphQL
mutation {
   users {
      create(input: { userName: "fooBar" password: "barFoo" })
      {
          user {
            id
            name
          }
      }
   }
}
```

**Comment by michaelstaib** [comment]
@kongkong56 I will close this issue. If you have any further question do not hesitate to ask. We also have a slack group.

https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTBkZjNjZWIzMmNlZjQ5MDQyNDNjMmY3NzYzZjgyYTVmZDU2YjVmNDlhNjNlNTk2ZWRiYzIxMTkwYzA4ODA5Yzg

**Comment by kongkong56** [comment]
the shema is like this:
mutation {
 user {
  id 
  name  
  userinfo {
   address
   phone
}
}

**Comment by michaelstaib** [comment]
That is supported. Though where exactly are you mutating here. It looks more like a query

**Comment by kongkong56** [comment]
![image](https://user-images.githubusercontent.com/3390474/54575010-777a5380-4a2d-11e9-8a07-93643451ee9c.png)
the mutation  docs is like this.

**Comment by michaelstaib** [comment]
This is a valid mutation that would work fine with Hot Chocolate. So, what is your actual problem? Maybe head over to our slack channel and we can try to sort your problem out.

https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTBkZjNjZWIzMmNlZjQ5MDQyNDNjMmY3NzYzZjgyYTVmZDU2YjVmNDlhNjNlNTk2ZWRiYzIxMTkwYzA4ODA5Yzg
