### ISSUE TITLE
Support for IQueryable<T> providers that do not support LongCount

### ISSUE THREAD

**Issue by GraemeF** [ChilliCream/hotchocolate#660]
**Is your feature request related to a problem? Please describe.**
I am trying to use HotChocolate with Azure CosmosDb via `DocumentClient`, which supports
`IQueryable<T>`. Unfortunately, although `Count` is supported, `LongCount` is not, so I get an error when I try to add pagination to a field. This happens at https://github.com/ChilliCream/hotchocolate/blob/b9ddf60a35f64527e9b49c527fdd62e2946ce28b/src/Core/Types/Types/Relay/QueryableConnectionResolver.cs#L52

**Describe the solution you'd like**
I would like `QueryableConnectionResolver<T>` to use or fall back to `Count` if `LongCount` is not supported.

**Describe alternatives you've considered**
It would be nice if `DocumentClient` and friends dealt with this themselves :)

**Comment by michaelstaib** [comment]
Hi @GraemeF,

I will check if we can get this into our patch release that will come on Sunday. If it is too much work for that release we will put it into our April release.

**Comment by GraemeF** [comment]
Awesome! I have got further by making my own clone of `CountQueryableConnectionResolver<T>` which uses `Count` but it then falls over when it later uses `Skip`, so it isn't the only problem that people will encounter. Changing `LongCount` would allow some operations to work, however, which would be a good thing!

**Comment by michaelstaib** [comment]
The problem with IQueryable is that the various operations are not guaranteed... I will look into how we can change the implementation so that it is not reliant on IQueryable. The algorithm of facebook is pretty straight forward for getting the start edges and so on ... os I will try to make it easier to provide alternative methods to slice the data.

But for our patch release I can only make minor changes. So, I might split this issue in two.

**Comment by michaelstaib** [comment]
But as a side-note, Microsoft will bring some slice methods to cosmos soon.

**Comment by GraemeF** [comment]
It seems like this is the problem `IQueryable` intended to solve, and it doesn't seem like `Count` and `Skip` are unreasonable operations for pagination to depend upon. Hopefully, as you say, support will improve soon!

**Comment by GraemeF** [comment]
For the benefit of anyone else who lands here, this is where MS seem to be communicating about pagination support in Cosmos DB: https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/6350987--documentdb-allow-paging-skip-take

**Comment by ChristianWeyer** [comment]
Seems Cosmos SQL API finally has the skip/take support: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-query-reference

**Comment by michaelstaib** [comment]
Yes we were testing that already in a private beta with Microsoft. Still we need to write some integration tests for cosmosDB and use the IntCount since not all databases support the long count. This one is not yer implemented but I think will follow in the next two previews of version 9 probably preview 30. Version 9 should be finished in the next two weeks. We are heavily working one the new documentation which will pick up lots of new areas.

**Comment by michaelstaib** [comment]
This one is now fixed with preview.40.
