### ISSUE TITLE
Verify that example projects work

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#769]

**Comment by jotatoledo** [comment]
I can confirm that the current example is missleading. 

The [current paths](https://github.com/ChilliCream/hotchocolate/blob/master/examples/AspNetCore.StarWars/Startup.cs#L70) used to configure the pipeline middlewares are wrong. For example, by using `app.UseGraphiQL("/graphiql")` the graphiql UI will be accesible at `localhost:XXXXX/graphiql/graphiql` instead of `localhost:XXXXX/graphiql/graphiql`, which Im pretty sure is not the decired result.

**Comment by michaelstaib** [comment]
Hi @jotatoledo,

The `app.UseGraphiQL("/graphql")` defines not the GraphiQL path but the query path of the GraphQL endpoint.

If you want to specify the actual location of GraphiQL you can do that through the options.

```CSharp
app.UseGrapghiQL(new GraphiQLOptions { QueryPath = "/graphql", Path = "/graphiql" }):
```

https://github.com/ChilliCream/hotchocolate/blob/master/src/Server/AspNetCore.GraphiQL/GraphiQLOptions.cs

**Comment by jotatoledo** [comment]
Hi @michaelstaib, thx for the quick response. I realized that yesterday after looking at the source code that you pointed :)

As I mentioned in the comment, it feels weird for example in the case of `app.UseGraphiQL("/graphql")` that the graphiql app will be located at `localhost:port/{queryPath}/graphiql`. 

Specifically, the concatenation at [this line](https://github.com/ChilliCream/hotchocolate/blob/master/src/Server/AspNetCore.GraphiQL/ApplicationBuilderExtensions.cs#L48) feels unnatural; IMO using `app.UseGraphiQL("/graphql")` should result in the graphiql app being located at `localhost:port/graphiql`

**Comment by michaelstaib** [comment]
The problem that I see with changing that is that we would break a lot of implementations out there. I think we should add more documentation and clarify that further.
