### ISSUE TITLE
StrictValidation false still enforces all resolvers

### ISSUE THREAD

**Issue by jkporter** [ChilliCream/hotchocolate#820]
**Describe the bug**
In version 8.x setting StrictValidation to false ignored missing resolvers. In 9.0.0 setting this to false results in errors when resolvers are not present.

**To Reproduce**
1. Create schema from string.
2. Set configuration.Option.StrictValidation = false;

**Expected behavior**
If there are missing resolvers there is no expection

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 9.0.0

**Comment by michaelstaib** [comment]
I will look into this tomorrow.

**Comment by michaelstaib** [comment]
Sorry for the delay here.... but I was pretty busy the last view days. I will look at this issue more closely today.

**Comment by jkporter** [comment]
Thanks for the reply and follow-up. Was a blocker for me but I ended writing a code generator to stub missing revolvers & models for my use case. Not what I envisioned but may actually turn out to be a good practice in the long run.

**Comment by michaelstaib** [comment]
There is a simpler way to work around this:


```csharp
SchemaBuilder.New()
   .Use(next => context => Task.CompletedTask)
   .Create()
```

The rule that we have is that you do not have to have a resolver actually but there must be some means registered to resolve data for a field. You can do that by providing one global middleware.

It works even if that middleware does not actually resolve data. We use that also in many of our tests.

This also allows to register one data middleware that pulls for a couple of fields data.

This is also how schema stitching works.

**Comment by spikyjt** [comment]
This is still a bug in v10.5.2.

The workaround info is use however, thanks @michaelstaib 

@jkporter I don't suppose you created a lib from that generator? Could you share the code? I'm trying to write an interface generator as there seems be nothing usable for .NET that's up to date for schema-first workflow.

**Comment by michaelstaib** [comment]
We will not change the behavior since I think the workaround is actually a good practice to handle this.

**Comment by spikyjt** [comment]
@michaelstaib When you say you won't change the behaviour, what is its intended behaviour? That doesn't seem clear - does it do anything? It could use some documentation.

The workaround is actually much less useful than I thought, because it overrides all resolvers, so although it is helpful for inspecting the schema, it is of no use if you want to get things up and running without having to implement all resolvers yet.

**Comment by michaelstaib** [comment]
StrictValidation was intended to shut off the validation of the schema but we are removing this option and let people opt into specific validation parts or even write validation on top. From the way where this is going, it just does not make sense anymore to have a global switch to shut the validation off.

My original intent with this was to have a switch to shut validation off when testing parts of the schema API.

What is it that you are trying to do? With version 11 we have a much more powerful configuration API that will let you rewrite the schema types by intercepting the configuration.

Also, just a side note, since you mentioned schema-first / sdl-first. We are also working on a lot more features around schema-first so if you want to chime in we can have a chat around this.

**Comment by spikyjt** [comment]
@michaelstaib I'd be very glad to have a chat about schema/sdl first approach and the features in v11. What's your preferred contact method?
