### ISSUE TITLE
Subscription State Storage

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#828]
We need a new abstraction that represents the state that each subscription has so that subscriptions can be recovered.

We have to have options for the storage so that the storage can automatically remove subscriptions after a subscription was not used for some time.

The subscription must allow to store some pointer information so that support for systems like Kafka or EventHub are easily possible.

We have to think about how we expose the pointer through the `IEventStream`.

Open Questions:

- How do we recover an `IEventStream`? Do we check the storage and the storage can then create a new stream instance?

**Comment by michaelstaib** [comment]
We should implement the storage with Redis and Mongo. 
- Subscriptions.Redis
- Subscriptions.Mongo

Each provider should be placed into a seperate library

**Comment by michaelstaib** [comment]
@glucaci what do you think?

**Comment by glucaci** [comment]
Yep sounds good, I have to check the current state and to see how and what we will save for the state and also for the stream in order to recover it.

For automatically removing the subscription we have to see if all providers have something like Mongo TTL Indexes, if not we have to implement an asynchronous service which will cleanup.

**Comment by tobias-tengler** [comment]
Closing, as a Redis storage has been implemented and I haven't heard anything about a planned MongoDB storage yet.
A newer issue should be created, if there are specific points that need to be addressed in this direction.
