### ISSUE TITLE
Apollo federation 

### ISSUE THREAD

**Issue by stalniy** [ChilliCream/hotchocolate#932]
**Is your feature request related to a problem? Please describe.**
Schema stitching is complicated and requires a lot of manual configuration. More about this in https://www.apollographql.com/docs/apollo-server/federation/migrating-from-stitching/#comparison-with-schema-stitching

**Describe the solution you'd like**
Apollo team recently suggested an alternative way to merge schemes. It’s called [Apollo federation](https://www.apollographql.com/docs/apollo-server/federation/introduction/). Requires almost no configuration and uses much simpler concept, actually it’s API Gateway + Query planner

**Update**:

[Federation spec](https://www.apollographql.com/docs/apollo-server/federation/federation-spec/)

**Comment by michaelstaib** [comment]
Hi @stalniy,

Hot Chocolate Schema Stitching and Apollo Schema Stitching are very different things. Schema stitching with HC works through directives almost like Apollo Federation does.

But also we are very different to Apollo Federation.

We think that the new approach of Apollo is good but we do want achieve more and allow people to have multiple representations of schemas. Also micro-service schemas should not have any knowledge of the bigger picture. micro-service schemas should only be concerned with their little universe.

We have started to build a completely new approach that we will release end of this year. We are currently reengineering our execution engine to work with query execution plans. This is very different from Apollo since we are putting that at the core of our GraphQL engine. That means that you will have execution plans no matter if you are building a GraphQL native server or a stitching gateway. In our proto-types we can see that this is supercharging database load.

Moreover, we want those extendable so that users can further optimize the execution plan handler. With the upcoming schema registry hc servers will be able to feed their execution plans into the schema registry and the schema registry can feed back reoptimized plans to the hc servers.

Furthermore, stitching with our new stitching layer will not involve any code, it is a real gateway that you can configure with our new GUI. It will allow you to completely rewrite source schemas into something new. Also you will be able to stitch-in OData and gGRPC services as well.

We are currently wrapping up version 10 (this used to be version 9.1) and will deliver the execution plans to the new execution engine with version 11 (this used to be version 9.2).

The new stitching layer will come out at the end of the year (version 12).

https://github.com/ChilliCream/hotchocolate/issues/871
https://github.com/ChilliCream/hotchocolate/issues/677
https://github.com/ChilliCream/hotchocolate/issues/642

We have played out our plan in this blog post:
https://chillicream.com/blog/2019/06/05/hot-chocolate-9.0.0 

Hope that gives you an outlook....

**Comment by stalniy** [comment]
Thanks for the quick reply and awesome project! I’ll definitely check the plans.
