### ISSUE TITLE
NullReferenceException thrown during context.AddError when failing to CompleteCompositeType

### ISSUE THREAD

**Issue by tunurgitr** [ChilliCream/hotchocolate#961]
**Describe the bug**
When executing a query with a schema defined by an interface with implementations registered, an error is thrown within the error reporting infrastructure.

**To Reproduce**
1. Define a code-first interface, but don't add the implementation types
2. Try to do a query that maps these interfaces

**Expected behavior**
A helpful error would be thrown indicating there was a problem mapping the CLR class to a registered type.

**Additional context**
https://github.com/ChilliCream/hotchocolate/blob/89b0a5d97a500e7fd6d16856987e417f524c6e42/src/Core/Core/Execution/Utilities/ValueCompletion.cs#L179

`context.Value` is null. Seems like it should be using the name of `type`.

![image](https://user-images.githubusercontent.com/1606109/62568345-d6583200-b841-11e9-950a-90fb72659865.png)

**Comment by michaelstaib** [comment]
I think the main issue here is that we create the schema in the first place since it is inconsistent.... let me check the spec first.

**Comment by michaelstaib** [comment]
OK, this is now fixed.

**Comment by michaelstaib** [comment]
So,

I have fixed also the execution engine code .... the `context.Value` was wrong in any way since that is the coerced output value. The type should be extracted from the `result` argument.

But I also added more context here.... the new error message is:
```
Could not resolve the actual object type from `System.String` for the abstract type `Bar`.
```

Apart from that the schema now validates interfaces more strict.

If you are in porto typing mode you can opt-out of the strictness with

```
SchemaBuilder
     ....
     .ModifyOption(o => o.StrictValidation = false)
     .Create()
```
